# PANDA packaging for SmallWorld.
#
# PANDA is the only major dependency that does not fit neatly into the
# `uv.lock` -> Python package flow:
# - it ships Python bindings (`pypanda`)
# - those bindings depend on native QEMU/PANDA shared libraries
# - some headers are generated by helper scripts instead of existing up front
#
# macOS is the awkward case. We can build most of SmallWorld natively there,
# but PANDA header generation still wants a Linux build environment. That is
# why this module sometimes routes `libpandaHeaders` through a Linux builder.
#
# The local patches in `nix/patches/` are intended to be temporary. Once the
# upstream PANDA/libpanda sources include the same fixes, this module should
# shrink down to a much simpler wrapper.
{
  lib,
  forEachSystem,
  panda-ng,
  pkgsFor,
}:

let
  # We follow PANDA's own flake.lock so our local wrapper uses the same
  # libpanda-ng and QEMU revisions that upstream PANDA expects.
  pandaNgLock = builtins.fromJSON (builtins.readFile "${panda-ng.outPath}/flake.lock");

  fetchLockedGitHubSource =
    pkgs: locked:
    pkgs.fetchFromGitHub {
      inherit (locked) owner repo rev;
      hash = locked.narHash;
    };

  # macOS hosts usually need Linux helper builds for generated PANDA headers.
  linuxBuilderSystemFor =
    system:
    if lib.hasSuffix "-darwin" system then
      lib.replaceStrings [ "-darwin" ] [ "-linux" ] system
    else
      system;
in
let
  packages = forEachSystem (
    system:
    let
      pkgs = pkgsFor system;
      linuxBuilderSystem = linuxBuilderSystemFor system;
      libExt = if pkgs.stdenv.hostPlatform.isDarwin then "dylib" else "so";
      # The PANDA plugin interface QEMU builds for us. Named once because
      # both the producer (`qemu.postInstall`) and the consumer
      # (`pypandaBuilder.postInstall`) have to agree on it.
      pandaPluginLib = "libpanda_plugin_interface.${libExt}";
      # `tree-sitter-grammars.tree-sitter-c` (used below to build PANDA's
      # headers) pulls in `datamodel-code-generator`, whose test suite pins
      # exact `ruff`-formatted golden output. A `ruff` version bump elsewhere
      # in nixpkgs can shift that formatting (e.g. blank-line placement) and
      # break the golden-file comparison, which has nothing to do with
      # whether the tool itself works. Skip its checks so that drift doesn't
      # block every package that merely depends on it as a build tool.
      #
      # `tree-sitter-c` itself also fails nixpkgs' newer
      # pythonMetadataCheckPhase: the derivation's `pname` doesn't match the
      # project name recorded in its own dist-info metadata, so the sanity
      # check raises `PackageNotFoundError` even though the module imports
      # fine. That mismatch is a pre-existing packaging quirk, not something
      # this project can fix upstream, so skip the check here too.
      pyPkgs = pkgs.python3Packages.overrideScope (
        _final: prev: {
          datamodel-code-generator = prev.datamodel-code-generator.overridePythonAttrs (_: {
            doCheck = false;
            doInstallCheck = false;
          });
          tree-sitter-grammars = prev.tree-sitter-grammars // {
            tree-sitter-c = prev.tree-sitter-grammars.tree-sitter-c.overridePythonAttrs (_: {
              dontCheckPythonMetadata = true;
            });
          };
        }
      );
      pandaQemuBaseSrc = fetchLockedGitHubSource pkgs pandaNgLock.nodes.panda-qemu-src.locked;
      pandaQemuSrc = pkgs.applyPatches {
        name = "panda-qemu-src";
        src = pandaQemuBaseSrc;
        # Normalize a few whitespace-only upstream defects before our local
        # patch applies, so the repo-local diff stays reviewable and passes
        # `git diff --check` without changing the effective source edits.
        prePatch = ''
          sed -i \
            -e 's/[[:space:]]\+$//' \
            -e 's/^\t/    /' \
            panda/src/panda_qemu_plugin_helpers.c
        '';
        patches = [
          ./patches/panda-qemu-tricore.patch
          ./patches/panda-qemu-remove-debug-printf.patch
          # SuperH, in two layers: `superh` adds the PANDA glue for QEMU's
          # existing SH-4 target, and `sh2a` then teaches that target the SH-2A
          # ISA. `sh2a` is generated on top of `superh` - they both touch
          # target/sh4/cpu.{h,c} - so this order matters.
          ./patches/panda-qemu-superh.patch
          ./patches/panda-qemu-sh2a.patch
        ];
      };
      libpandaNgSrc = fetchLockedGitHubSource pkgs pandaNgLock.nodes.libpanda-ng-src.locked;
      # Keep the upstream source intact and layer our temporary local fixes
      # on top so it is obvious what can be deleted later.
      pandaNgSrc = pkgs.applyPatches {
        name = "panda-ng-src";
        src = panda-ng.outPath;
        patches = [
          ./patches/panda-ng-darwin.patch
          ./patches/panda-ng-tricore.patch
          ./patches/panda-ng-superh.patch
        ];
      };
      targetList = [
        "x86_64-softmmu"
        "i386-softmmu"
        "arm-softmmu"
        "aarch64-softmmu"
        "tricore-softmmu"
        "ppc-softmmu"
        "mips-softmmu"
        "mipsel-softmmu"
        "mips64-softmmu"
        "ppc64-softmmu"
        "mips64el-softmmu"
        "loongarch64-softmmu"
        "riscv32-softmmu"
        "riscv64-softmmu"
        # Both SuperH endiannesses. SmallWorld only exposes SH-2A big-endian
        # (`sh4eb`), because sleigh has no little-endian SH-2A language, but note
        # that `panda-qemu-sh2a.patch` registers `sh7264`/`sh7269` in
        # `target/sh4/cpu.c` with no `TARGET_BIG_ENDIAN` guard, so the
        # little-endian `sh4-softmmu` build carries them too. There is no
        # SmallWorld machdef, platform def or Ghidra language for that
        # combination, so do not reach for it via `arg_overrides`.
        "sh4-softmmu"
        "sh4eb-softmmu"
      ];
      qemuConfigureFlags = [
        "--enable-plugins"
        "--disable-containers"
        "--target-list=${builtins.concatStringsSep "," targetList}"
      ];
      libpandaHeaderNativeBuildInputs = with pkgs; [
        pkg-config
        gdb
        pyPkgs.python
        pyPkgs.cffi
        pyPkgs.tree-sitter
        pyPkgs.tree-sitter-grammars.tree-sitter-c
      ];
      # This keeps our libpanda-ng source in sync with the QEMU branch PANDA
      # currently expects, then adds one more local patch for builder usage.
      libpandaPatch = pkgs.fetchpatch {
        url = "https://patch-diff.githubusercontent.com/raw/panda-re/libpanda-ng/pull/3.diff";
        hash = "sha256-FN1OUdRhOIK+meOlJH9kPysjrM50qYQVnl/Ll6zGF6w=";
        revert = true;
      };
      libpandaSrc = pkgs.applyPatches {
        name = "libpanda-ng-src";
        src = libpandaNgSrc;
        patches = [
          libpandaPatch
          ./patches/libpanda-build-linux-builder.patch
          ./patches/libpanda-superh.patch
        ];
      };
      qemuSubprojects = pkgs.stdenv.mkDerivation {
        name = "qemu-subprojects";
        version = "main";
        src = pandaQemuSrc;
        nativeBuildInputs = with pkgs; [
          meson
          git
          cacert
        ];
        buildCommand = ''
          mkdir -pv work
          cp -r --no-preserve=mode $src/meson.build work/
          cp -r --no-preserve=mode $src/meson_options.txt work/
          cp -r --no-preserve=mode $src/subprojects work/subprojects

          pushd work
          meson subprojects download
          find subprojects -type d -name .git -prune -execdir rm -r {} +
          popd

          cp -r work/subprojects $out
        '';
        outputHash = "sha256-eUw7yBWxRKJbfhKvZDRNpTSaxrnDYr31Tkx35Myx4Fs=";
        outputHashAlgo = "sha256";
        outputHashMode = "recursive";
      };
      # `pkgs.qemu` carries nixpkgs patches written against the exact QEMU
      # release nixpkgs pins. We swap in PANDA's QEMU fork, whose tree has
      # drifted from that release, so a nixpkgs bump can introduce a patch
      # that no longer applies here and breaks the whole PANDA stack for
      # reasons unrelated to SmallWorld.
      #
      # Drop such patches when they only touch upstream's test suite: we
      # build with an explicit `--target-list` and never build or run qtest,
      # so they cannot affect the QEMU binaries or the PANDA plugin
      # interfaces we actually consume. Patches that touch real sources must
      # be rebased instead of listed here.
      droppedQemuPatches = [
        # Relocates an `#ifdef CONFIG_TASN1` guard in
        # `tests/qtest/migration/tls-tests.c`; PANDA's fork has moved that
        # code, so hunks 2 and 3 fail to apply.
        "fix-tls-tests-without-tasn1.patch"
      ];
      keepQemuPatch =
        patch:
        let
          name = builtins.baseNameOf (toString patch);
        in
        !(lib.any (dropped: lib.hasSuffix dropped name) droppedQemuPatches);
      # Store paths for fetched patches carry a hash prefix, so match on the
      # trailing filename rather than requiring an exact basename.
      #
      # Say something when an entry stops matching, so the drop list does not
      # quietly rot into a no-op. Warn rather than throw: nixpkgs marks these
      # patches "remove when included in a release", so the common case is
      # that the patch simply disappears - at which point there is nothing
      # left to drop and the build is fine. Only a rename would actually hurt,
      # and failing eval outright would turn every routine upstream cleanup
      # into a broken flake.
      pandaQemuPatches =
        old:
        let
          patches = old.patches or [ ];
          names = map (patch: builtins.baseNameOf (toString patch)) patches;
          unmatched = lib.filter (
            dropped: !(lib.any (name: lib.hasSuffix dropped name) names)
          ) droppedQemuPatches;
        in
        lib.warnIf (unmatched != [ ])
          "nix/panda-packages.nix: droppedQemuPatches entries match no nixpkgs qemu patch (stale, or renamed upstream): ${lib.concatStringsSep ", " unmatched}"
          (builtins.filter keepQemuPatch patches);
      mkQemuSourceSetup =
        {
          includeLibpanda ? false,
        }:
        ''
          cp -r --no-preserve=mode ${qemuSubprojects}/. "./$sourceRoot/subprojects/"
          ${lib.optionalString includeLibpanda ''
            cp -r --no-preserve=mode ${libpandaSrc} ./libpanda-ng
          ''}
          patchShebangs "./$sourceRoot/scripts"${lib.optionalString includeLibpanda " ./libpanda-ng"}
        '';
      qemu = pkgs.qemu.overrideAttrs (old: {
        version = "main";
        src = pandaQemuSrc;
        patches = pandaQemuPatches old;
        configureFlags = qemuConfigureFlags;
        # nixpkgs now drives QEMU through `make` instead of the ninja setup
        # hook. The ninja hook parallelised by default; the generic make
        # `buildPhase` only passes `-j` when `enableParallelBuilding` is set,
        # and without a `-j` QEMU's own Makefile hands ninja `-j1`. Say it
        # explicitly so the build does not silently go serial.
        enableParallelBuilding = true;
        postUnpack = (old.postUnpack or "") + "\n" + mkQemuSourceSetup { };
        # QEMU's meson build tree lives in `$sourceRoot/build`. nixpkgs used
        # to `cd build` in `preBuild`, so install hooks ran inside that tree;
        # since it switched to a make-driven ninja build they run from the
        # source root instead. Accept either cwd so a nixpkgs bump in either
        # direction doesn't break this copy, and say which places were tried
        # when neither has the plugin - that is the "QEMU never built it" case,
        # which is a different problem from the build tree having moved again.
        postInstall =
          (old.postInstall or "")
          + "\n"
          + ''
            pandaPluginDir=
            for candidate in contrib/plugins build/contrib/plugins; do
              if [ -f "$candidate/${pandaPluginLib}" ]; then
                pandaPluginDir=$candidate
                break
              fi
            done
            if [ -z "$pandaPluginDir" ]; then
              echo "error: ${pandaPluginLib} is in neither contrib/plugins nor build/contrib/plugins (cwd: $PWD)." >&2
              echo "QEMU did not build the PANDA plugin interface." >&2
              exit 1
            fi
            mkdir -p "$out/lib"
            cp -v "$pandaPluginDir/${pandaPluginLib}" "$out/lib/"
          '';
      });
      # `libpanda-ng/run_all.sh` generates the headers consumed by the PANDA
      # bindings, so this is not a simple "copy include files" step.
      libpandaHeaders =
        if pkgs.stdenv.hostPlatform.isLinux then
          pkgs.qemu.overrideAttrs (old: {
            pname = "libpanda-ng-headers";
            version = "main";
            outputs = [ "out" ];
            separateDebugInfo = false;
            src = pandaQemuSrc;
            patches = pandaQemuPatches old;
            dontFixup = true;
            nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ libpandaHeaderNativeBuildInputs;
            configureFlags = qemuConfigureFlags;
            # See the note on `qemu` above: without this the make-driven build
            # runs ninja at `-j1`.
            enableParallelBuilding = true;
            postUnpack =
              (old.postUnpack or "")
              + "\n"
              + mkQemuSourceSetup {
                includeLibpanda = true;
              };
            # `postUnpack` drops `libpanda-ng` next to the unpacked source, and
            # `sourceRoot` is relative to the same directory, so anchor both on
            # `$NIX_BUILD_TOP` rather than assuming `$TMPDIR` is the same path.
            postBuild =
              (old.postBuild or "")
              + "\n"
              + ''
                mkdir -pv "$NIX_BUILD_TOP/libpanda-ng/build"
                pushd "$NIX_BUILD_TOP/libpanda-ng/build"
                bash ../run_all.sh "$NIX_BUILD_TOP/$sourceRoot"
                popd
              '';
            installPhase = ''
              runHook preInstall
              mkdir -pv $out/include
              cp -v "$NIX_BUILD_TOP"/libpanda-ng/build/*.h $out/include/
              runHook postInstall
            '';
            postInstall = "";
          })
        else
          # On Darwin, reuse the matching Linux builder result rather than
          # trying to run the header generator directly on the host.
          packages.${linuxBuilderSystem}.libpandaHeaders;
      panda = pkgs.stdenv.mkDerivation {
        name = "panda";
        version = "main";
        src = pandaNgSrc;
        nativeBuildInputs = with pkgs; [
          pkg-config
          meson
          ninja
          cargo
        ];
        buildInputs = with pkgs; [
          glib
          curl
          pyPkgs.python
          pyPkgs.pycparser
        ];
        mesonFlags = [
          "-Dcpp_std=gnu++17"
          (pkgs.lib.strings.mesonOption "targets" (builtins.concatStringsSep "," targetList))
        ];
        preConfigure = ''
          mkdir -p local_packages
          ln -s ${libpandaHeaders}/include local_packages/panda-ng
        '';
        preInstall = ''
          cp plugins/*/*.h plugins/
          for dir in plugins/rust/rust_skeleton/*; do
            arch=$(basename $dir)
            cp -r $dir plugins/rust_rust_skeleton_$arch
          done
        '';
        postInstall = ''
          mkdir -pv $out/lib/panda/panda
          mv $out/plugin $out/lib/panda/panda/plugins
        '';
      };
      pypandaBuilder =
        ps:
        ps.buildPythonPackage {
          pname = "pandare2";
          version = "main";
          format = "setuptools";
          src = "${pandaNgSrc}/python/core";
          propagatedBuildInputs = with ps; [
            cffi
            colorama
          ];
          preBuild = ''
            substituteInPlace setup.py --replace-fail /usr/include/panda-ng ${libpandaHeaders}/include
            grep 'plugin_dir =' setup.py
            sed -i 's,plugin_dir = .*,plugin_dir="${pandaNgSrc}/plugins",' setup.py
          '';
          postInstall = ''
            mkdir -pv $out/lib/qemu/build
            cp -R ${qemu}/lib/libpanda-*.${libExt} $out/lib/qemu/build/
            mkdir -pv $out/lib/qemu/build/contrib/plugins
            cp -R ${qemu}/lib/${pandaPluginLib} $out/lib/qemu/build/contrib/plugins/
            mkdir -pv $out/lib/qemu/pc-bios
            cp -R ${qemu}/share/qemu/*.rom ${qemu}/share/qemu/*.bin $out/lib/qemu/pc-bios/
          '';
        };
      pypanda = pypandaBuilder pyPkgs;
    in
    {
      inherit
        libpandaHeaders
        panda
        pypanda
        pypandaBuilder
        qemu
        qemuSubprojects
        ;
    }
  );
in
packages
