FROM docker-registry.docker-registry.svc.cluster.local:5000/smallworld/smallworld_deps:latest

# Install smallworld
COPY ./ /opt/smallworld/

WORKDIR /opt/smallworld/tests
RUN apt -y install $(cat ./dependencies/apt.txt)
