ARG DOCKER_REGISTRY=harbor.harbor.svc.cluster.local
FROM ${DOCKER_REGISTRY}/smallworld/smallworld_deps:latest

# Install smallworld
COPY ./ /opt/smallworld/

WORKDIR /opt/smallworld/tests
RUN pip install -e ".[development]" -c constraints.txt

WORKDIR /opt/smallworld/tests
RUN apt-get -y install $(cat ./dependencies/apt.txt) && apt-get clean
