name: Tag

on:
  push:
    tags: 
      - 'v*'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[development] -c constraints.txt
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Notes
        run: |
          VERSION=${GITHUB_REF/refs\/tags\/v/}
          sed "1,/## \[$VERSION\]/d;/\[/Q" CHANGELOG.md > RELEASE-CHANGES.md
      - name: Release (Draft)
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE-CHANGES.md
          files: dist/*
          draft: true
