# type: ignore
from colorizer_test import test

from smallworld.analyses.colorizer_read_write import RegisterInfo
from smallworld.hinting.hints import (
    DynamicMemoryValueSummaryHint,
    DynamicRegisterValueSummaryHint,
    TraceExecutionHint,
)
from smallworld.platforms.defs.platformdef import RegisterDef

if __name__ == "__main__":
    # test(num_insn, buflen, create_heap, fortytwos randomize_regs, seed)
    #
    # foo function in ahme.c (trace_executor dir) is what is
    # harnessed / analyzed by the test function
    #
    # Also, buflen bigger than min color 0x80 thus we *will* actually
    # get derivation for buflen back to esi (2nd arg to foo).
    #
    derivations, hints = test(
        5,  # num micro executions
        100,  # max instructions per micro execution
        0x80 + 1,  # buffer length (not 47 here, which is magic)
        # also, bigger than min color so that we can analyze it
        False,  # buffer needn't contain a lot of 42s since we arent in magic bit
        1234,  # seed (since `test` generates a random buffer)
    )

    # collect all pcs in any trace
    # also tds which is set of digests for a trace
    tds = set([])
    i = 0
    all_pcs = set([])
    for h in hints:
        if type(h) is TraceExecutionHint:
            tds.add(h.trace_digest)
            for te in h.trace:
                all_pcs.add(te.pc)
            i += 1

    num_expected = 0
    num_unexpected = 0

    def expected(cond, msge, msgu):
        global num_expected, num_unexpected
        if cond:
            print(f"EXPECTED  {msge}")
            num_expected += 1
            return True
        else:
            print(f"UNEXPECTED {msgu}")
            num_unexpected += 1
            return False

    truth_all_pcs = {
        0x2209,
        0x2210,
        0x2212,
        0x2215,
        0x2218,
        0x221C,
        0x221F,
        0x2222,
        0x2227,
        0x2229,
        0x222B,
        0x222F,
        0x2232,
        0x2234,
        0x2237,
        0x2239,
        0x223B,
        0x223E,
        0x2240,
        0x2242,
        0x2244,
        0x2247,
        0x224A,
        0x224E,
        0x2251,
        0x2254,
        0x2159,
        0x215A,
        0x215D,
        0x2161,
        0x2164,
        0x2167,
        0x216E,
        0x2172,
    }

    expected(
        all_pcs == truth_all_pcs,
        "set of pcs is same for truth and observed",
        "set of pcs disagrees between truth and observed",
    )

    expected(
        i == 5, "five trace execution hints", f"{i} trace execution hints. 5 expected"
    )

    expected(
        len(tds) == 1,
        "1 unique trace",
        f"num unique traces is {len(tds)}. 1 expected",
    )

    observed_summ = {}
    for h in hints:
        if type(h) in set(
            [DynamicMemoryValueSummaryHint, DynamicRegisterValueSummaryHint]
        ):
            if h.pc not in observed_summ:
                observed_summ[h.pc] = []
            observed_summ[h.pc].append(h)

    observed_summ_pcs = set(list(observed_summ.keys()))

    truth_summ = {
        8537: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8537,
                color=1,
                size=8,
                use=False,
                new=False,
                count=5,
                dynamic_values=[
                    4885445162691904961,
                    13460321687654991269,
                    9280256056959569510,
                    9814421962479061546,
                    18306165297079870698,
                ],
                num_micro_executions=5,
                base="rsp",
                index="None",
                scale=1,
                offset=0,
                addresses=[81912],
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8537,
                color=3,
                size=8,
                use=False,
                new=True,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rsp",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-def-summary",
                pc=8537,
                color=1,
                size=8,
                use=True,
                new=True,
                count=5,
                dynamic_values=[
                    4885445162691904961,
                    13460321687654991269,
                    9280256056959569510,
                    9814421962479061546,
                    18306165297079870698,
                ],
                num_micro_executions=5,
                reg_name="rbp",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-def-summary",
                pc=8537,
                color=2,
                size=8,
                use=True,
                new=True,
                count=5,
                dynamic_values=[81920],
                num_micro_executions=5,
                reg_name="rsp",
            ),
        ],
        8541: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8541,
                color=4,
                size=8,
                use=False,
                new=False,
                count=5,
                dynamic_values=[131072],
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-24,
                addresses=[81888],
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8541,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-def-summary",
                pc=8541,
                color=4,
                size=8,
                use=True,
                new=True,
                count=5,
                dynamic_values=[131072],
                num_micro_executions=5,
                reg_name="rdi",
            ),
        ],
        8545: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8545,
                color=5,
                size=4,
                use=False,
                new=False,
                count=5,
                dynamic_values=[129],
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-28,
                addresses=[81884],
            ),
            DynamicRegisterValueSummaryHint(
                message="read-def-summary",
                pc=8545,
                color=5,
                size=4,
                use=True,
                new=True,
                count=5,
                dynamic_values=[129],
                num_micro_executions=5,
                reg_name="esi",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8545,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8548: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8548,
                color=6,
                size=4,
                use=False,
                new=False,
                count=5,
                dynamic_values=[
                    2558659334,
                    3585948327,
                    1698482380,
                    2568261659,
                    2583265852,
                ],
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-32,
                addresses=[81880],
            ),
            DynamicRegisterValueSummaryHint(
                message="read-def-summary",
                pc=8548,
                color=6,
                size=4,
                use=True,
                new=True,
                count=5,
                dynamic_values=[
                    2558659334,
                    3585948327,
                    1698482380,
                    2568261659,
                    2583265852,
                ],
                num_micro_executions=5,
                reg_name="edx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8548,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8558: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8558,
                color=5,
                size=4,
                use=True,
                new=False,
                count=5,
                dynamic_values=[129],
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-28,
                addresses=[81884],
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8558,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8728: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8728,
                color=4,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[131072],
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-24,
                addresses=[81888],
            ),
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8728,
                color=4,
                size=8,
                use=False,
                new=False,
                count=5,
                dynamic_values=[131072],
                num_micro_executions=5,
                reg_name="rax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8728,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8735: [
            DynamicMemoryValueSummaryHint(
                message="read-def-summary",
                pc=8735,
                color=7,
                size=1,
                use=True,
                new=True,
                count=5,
                dynamic_values=[
                    199,
                    232,
                    136,
                    138,
                    203,
                    142,
                    176,
                    244,
                    150,
                    247,
                    248,
                    185,
                ],
                num_micro_executions=5,
                base="rax",
                index="None",
                scale=1,
                offset=0,
                addresses=[131072, 131073, 131074, 131075],
            ),
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8735,
                color=7,
                size=4,
                use=False,
                new=False,
                count=5,
                dynamic_values=[
                    199,
                    232,
                    136,
                    138,
                    203,
                    142,
                    176,
                    244,
                    150,
                    247,
                    248,
                    185,
                ],
                num_micro_executions=5,
                reg_name="edx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8735,
                color=4,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[131072, 131073, 131074, 131075],
                num_micro_executions=5,
                reg_name="rax",
            ),
        ],
        8775: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8775,
                color=12,
                size=4,
                use=False,
                new=False,
                count=2,
                dynamic_values=[4294967284, 4294967293],
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-4,
                addresses=[81908],
            ),
            DynamicMemoryValueSummaryHint(
                message="write-def-summary",
                pc=8775,
                color=19,
                size=4,
                use=False,
                new=True,
                count=3,
                dynamic_values=[4294967288, 4294967260, 4294967276, 4294967291],
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-4,
                addresses=[81908],
            ),
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8775,
                color=12,
                size=4,
                use=True,
                new=False,
                count=3,
                dynamic_values=[4294967276, 4294967291, 4294967284, 4294967293],
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-4,
                addresses=[81908],
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8775,
                color=12,
                size=4,
                use=True,
                new=False,
                count=5,
                dynamic_values=[
                    4294967280,
                    4294967284,
                    4294967288,
                    4294967290,
                    4294967292,
                    4294967293,
                    4294967294,
                ],
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8775,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8785: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8785,
                color=5,
                size=4,
                use=True,
                new=False,
                count=5,
                dynamic_values=[129],
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-28,
                addresses=[81884],
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8785,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8538: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8538,
                color=3,
                size=8,
                use=False,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8538,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rsp",
            ),
        ],
        8551: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8551,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8713: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8713,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8722: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8722,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8732: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8732,
                color=4,
                size=8,
                use=False,
                new=False,
                count=5,
                dynamic_values=[131072],
                num_micro_executions=5,
                reg_name="rax",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8732,
                color=17,
                size=8,
                use=False,
                new=True,
                count=5,
                dynamic_values=[131073, 131074, 131075],
                num_micro_executions=5,
                reg_name="rax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8732,
                color=4,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[131072],
                num_micro_executions=5,
                reg_name="rax",
            ),
        ],
        8745: [
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8745,
                color=18,
                size=1,
                use=False,
                new=True,
                count=4,
                dynamic_values=[161, 230, 168, 144, 243, 246, 214, 191],
                num_micro_executions=5,
                reg_name="al",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8745,
                color=7,
                size=1,
                use=True,
                new=False,
                count=5,
                dynamic_values=[
                    199,
                    232,
                    136,
                    138,
                    203,
                    142,
                    176,
                    244,
                    150,
                    247,
                    248,
                    185,
                ],
                num_micro_executions=5,
                reg_name="dl",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8745,
                color=8,
                size=2,
                use=False,
                new=True,
                count=5,
                dynamic_values=[
                    15367,
                    58639,
                    1936,
                    15125,
                    1815,
                    51742,
                    12705,
                    62632,
                    55856,
                    64568,
                    51258,
                    64447,
                    51016,
                    64084,
                    726,
                    52710,
                    7018,
                    56945,
                    59123,
                    4598,
                ],
                num_micro_executions=5,
                reg_name="ax",
            ),
        ],
        8747: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8747,
                color=10,
                size=2,
                use=False,
                new=False,
                count=1,
                dynamic_values=[251],
                num_micro_executions=5,
                reg_name="ax",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8747,
                color=9,
                size=2,
                use=False,
                new=True,
                count=5,
                dynamic_values=[229, 230, 199, 200, 218, 202, 205, 244, 250, 252, 222],
                num_micro_executions=5,
                reg_name="ax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8747,
                color=8,
                size=2,
                use=True,
                new=False,
                count=5,
                dynamic_values=[
                    15367,
                    58639,
                    1936,
                    15125,
                    1815,
                    51742,
                    12705,
                    62632,
                    55856,
                    64568,
                    51258,
                    64447,
                    51016,
                    64084,
                    726,
                    52710,
                    7018,
                    56945,
                    59123,
                    4598,
                ],
                num_micro_executions=5,
                reg_name="ax",
            ),
        ],
        8751: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8751,
                color=11,
                size=1,
                use=False,
                new=False,
                count=2,
                dynamic_values=[248, 249, 255],
                num_micro_executions=5,
                reg_name="al",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8751,
                color=10,
                size=1,
                use=False,
                new=True,
                count=5,
                dynamic_values=[249, 251, 252, 254, 255],
                num_micro_executions=5,
                reg_name="al",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8751,
                color=9,
                size=1,
                use=True,
                new=False,
                count=5,
                dynamic_values=[
                    229,
                    230,
                    199,
                    200,
                    218,
                    202,
                    205,
                    244,
                    250,
                    251,
                    252,
                    222,
                ],
                num_micro_executions=5,
                reg_name="al",
            ),
        ],
        8754: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8754,
                color=7,
                size=4,
                use=False,
                new=False,
                count=5,
                dynamic_values=[
                    199,
                    232,
                    136,
                    138,
                    203,
                    142,
                    176,
                    244,
                    150,
                    247,
                    248,
                    185,
                ],
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8754,
                color=7,
                size=4,
                use=True,
                new=False,
                count=5,
                dynamic_values=[
                    199,
                    232,
                    136,
                    138,
                    203,
                    142,
                    176,
                    244,
                    150,
                    247,
                    248,
                    185,
                ],
                num_micro_executions=5,
                reg_name="edx",
            ),
        ],
        8756: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8756,
                color=11,
                size=1,
                use=False,
                new=False,
                count=5,
                dynamic_values=[255],
                num_micro_executions=5,
                reg_name="cl",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8756,
                color=11,
                size=1,
                use=False,
                new=True,
                count=4,
                dynamic_values=[255],
                num_micro_executions=5,
                reg_name="cl",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8756,
                color=7,
                size=1,
                use=True,
                new=False,
                count=5,
                dynamic_values=[
                    199,
                    232,
                    136,
                    138,
                    203,
                    142,
                    176,
                    244,
                    150,
                    247,
                    248,
                    185,
                ],
                num_micro_executions=5,
                reg_name="cl",
            ),
        ],
        8759: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8759,
                color=12,
                size=4,
                use=False,
                new=False,
                count=2,
                dynamic_values=[4294967290],
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8759,
                color=12,
                size=4,
                use=False,
                new=True,
                count=4,
                dynamic_values=[
                    4294967289,
                    4294967290,
                    4294967292,
                    4294967293,
                    4294967295,
                ],
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8759,
                color=10,
                size=4,
                use=True,
                new=False,
                count=5,
                dynamic_values=[248, 249, 251, 252, 254, 255],
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8759,
                color=11,
                size=4,
                use=True,
                new=False,
                count=5,
                dynamic_values=[255],
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8761: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8761,
                color=12,
                size=4,
                use=False,
                new=False,
                count=4,
                dynamic_values=[
                    4294967289,
                    4294967290,
                    4294967292,
                    4294967293,
                    4294967295,
                ],
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8761,
                color=12,
                size=4,
                use=True,
                new=False,
                count=4,
                dynamic_values=[
                    4294967289,
                    4294967290,
                    4294967292,
                    4294967293,
                    4294967295,
                ],
                num_micro_executions=5,
                reg_name="eax",
            ),
        ],
        8763: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8763,
                color=13,
                size=4,
                use=False,
                new=False,
                count=1,
                dynamic_values=[4294967200],
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8763,
                color=13,
                size=4,
                use=False,
                new=True,
                count=4,
                dynamic_values=[
                    4294967232,
                    4294967200,
                    4294967280,
                    4294967184,
                    4294967248,
                ],
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8763,
                color=12,
                size=4,
                use=True,
                new=False,
                count=4,
                dynamic_values=[
                    4294967289,
                    4294967290,
                    4294967292,
                    4294967293,
                    4294967295,
                ],
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8766: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8766,
                color=14,
                size=4,
                use=False,
                new=False,
                count=1,
                dynamic_values=[4294967194],
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8766,
                color=14,
                size=4,
                use=False,
                new=True,
                count=4,
                dynamic_values=[4294967194, 4294967228, 4294967245],
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8766,
                color=12,
                size=4,
                use=True,
                new=False,
                count=4,
                dynamic_values=[4294967290, 4294967292, 4294967293],
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8766,
                color=13,
                size=4,
                use=True,
                new=False,
                count=4,
                dynamic_values=[4294967232, 4294967200, 4294967248],
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8768: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8768,
                color=7,
                size=4,
                use=False,
                new=False,
                count=5,
                dynamic_values=[199, 138, 203, 142, 176, 244, 150, 248, 185],
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8768,
                color=7,
                size=4,
                use=True,
                new=False,
                count=5,
                dynamic_values=[199, 138, 203, 142, 176, 244, 150, 248, 185],
                num_micro_executions=5,
                reg_name="edx",
            ),
        ],
        8770: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8770,
                color=10,
                size=4,
                use=False,
                new=False,
                count=3,
                dynamic_values=[248, 252, 244],
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8770,
                color=15,
                size=4,
                use=False,
                new=True,
                count=4,
                dynamic_values=[240, 244, 250, 253, 254],
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8770,
                color=7,
                size=4,
                use=True,
                new=False,
                count=5,
                dynamic_values=[199, 138, 203, 142, 176, 244, 150, 248, 185],
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8770,
                color=14,
                size=4,
                use=True,
                new=False,
                count=4,
                dynamic_values=[4294967194, 4294967228, 4294967245],
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8772: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8772,
                color=15,
                size=1,
                use=True,
                new=False,
                count=5,
                dynamic_values=[240, 244, 248, 250, 252, 253, 254],
                num_micro_executions=5,
                reg_name="al",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8772,
                color=12,
                size=4,
                use=False,
                new=True,
                count=5,
                dynamic_values=[
                    4294967280,
                    4294967284,
                    4294967288,
                    4294967290,
                    4294967292,
                    4294967293,
                    4294967294,
                ],
                num_micro_executions=5,
                reg_name="eax",
            ),
        ],
        8778: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8778,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8782: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8782,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                dynamic_values=[81912],
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
    }

    truth_summ_pcs = set(list(truth_summ.keys()))
    expected(
        truth_summ_pcs == observed_summ_pcs,
        "set of pcs observed for summary hints same as truth",
        "pcs observed for summary hints not same as truth",
    )

    for pc in all_pcs:
        if pc in truth_summ_pcs and pc in observed_summ_pcs:
            if not expected(
                observed_summ[pc] == truth_summ[pc],
                f"list of summary hints observed for pc={pc} same as truth",
                f"list of summary hints observed for pc={pc} not same as for truth",
            ):
                print(f"Truth:    {truth_summ[pc]}")
                print(f"Observed: {observed_summ[pc]}")
        elif pc in truth_summ_pcs:
            print(f"{truth_summ[pc]} is in truth only")
        elif pc in observed_summ_pcs:
            print(f"{observed_summ[pc]} in observed only")
        else:
            pass

    correct_derivations = [
        (
            8735,
            "rax",
            {
                RegisterInfo(
                    color=3, is_new=True, register=RegisterDef(name="rdi", size=8)
                )
            },
        ),
        (8604, "rax", set()),
        (8688, "al", set()),
        (8579, "[rbp-0x18]", set()),
        (
            8558,
            "[rbp-0x1c]",
            {
                RegisterInfo(
                    color=4, is_new=True, register=RegisterDef(name="esi", size=4)
                )
            },
        ),
        (8568, "[rbp-0x20]", set()),
    ]

    for i in range(6):
        cpc, cvals, cder = correct_derivations[i]
        opc, ovals, oder = derivations[i]
        expected(
            (cpc == opc) and (cvals == ovals) and (cder == oder),
            f"derivation for {cvals} @ {cpc:x} is correct: {cder}",
            f"derivation for {cvals} @ {cpc:x} is incorrect: {oder}",
        )

    expected(
        num_unexpected == 0,
        "No unexpected results",
        f"{num_unexpected} unexpected results",
    )
