from colorizer_test import test

from smallworld.hinting.hints import (
    DefUseGraphHint,
    DynamicMemoryValueSummaryHint,
    DynamicRegisterValueSummaryHint,
)

if __name__ == "__main__":
    # test(num_insn, buflen, create_heap, fortytwos, randomize_regs, seed):
    hints = test(10, 37, 13, True, 1234)

    summh = [
        h
        for h in hints
        if type(h)
        in set([DynamicMemoryValueSummaryHint, DynamicRegisterValueSummaryHint])
    ]

    # put them in a canonical order by their string repr
    def cmpf(h):
        return (h.pc, str(type(h)), h.message, str(h))

    summh.sort(key=cmpf)

    summary_hints_truth = [
        DynamicRegisterValueSummaryHint(
            message="read-def-summary",
            pc=8589,
            color=1,
            size=8,
            use=True,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="rsp",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8589,
            color=2,
            size=8,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="rsp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8590,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rsp",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8590,
            color=2,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicMemoryValueSummaryHint(
            message="write-copy-summary",
            pc=8593,
            color=3,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            base="rbp",
            index="None",
            scale=1,
            offset=-24,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-def-summary",
            pc=8593,
            color=3,
            size=8,
            use=True,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="rdi",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8593,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8597,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicMemoryValueSummaryHint(
            message="write-copy-summary",
            pc=8600,
            color=4,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            base="rbp",
            index="None",
            scale=1,
            offset=-32,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-def-summary",
            pc=8600,
            color=4,
            size=4,
            use=True,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="edx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8600,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8603,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8610,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8765,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8774,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicMemoryValueSummaryHint(
            message="read-flow-summary",
            pc=8780,
            color=3,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            base="rbp",
            index="None",
            scale=1,
            offset=-24,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8780,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8780,
            color=3,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8784,
            color=3,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8784,
            color=3,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicMemoryValueSummaryHint(
            message="read-def-summary",
            pc=8787,
            color=5,
            size=1,
            use=True,
            new=True,
            count=10,
            num_micro_executions=10,
            base="rax",
            index="None",
            scale=1,
            offset=0,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8787,
            color=3,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8787,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="edx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8790,
            color=6,
            size=4,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8795,
            color=6,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8795,
            color=6,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8797,
            color=5,
            size=1,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="dl",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8797,
            color=6,
            size=1,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="al",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8797,
            color=7,
            size=2,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="ax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8799,
            color=7,
            size=2,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8806,
            color=5,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="edx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8806,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8808,
            color=5,
            size=1,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="cl",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8813,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8818,
            color=5,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8818,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8821,
            color=5,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8821,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8823,
            color=5,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="edx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8823,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8825,
            color=5,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8825,
            color=5,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8830,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8833,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8837,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8840,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
    ]

    res1 = summh == summary_hints_truth
    print(f"Summary hints match: {res1}")

    defuseghl = [h for h in hints if type(h) is DefUseGraphHint]

    res2 = len(defuseghl) == 1
    print(f"Got a single def-use graph: {res2}")

    defusegh = defuseghl[0]

    defuseg_hint_truth = DefUseGraphHint(
        message="concrete-summary-def-use-graph",
        graph={
            "directed": True,
            "multigraph": True,
            "graph": {},
            "nodes": [
                {"id": 8787},
                {"id": "input color-5 *(rax)_init"},
                {"id": 8589},
                {"id": "input color-1 rsp_init"},
                {"id": 8593},
                {"id": "input color-3 rdi_init"},
                {"id": 8600},
                {"id": "input color-4 edx_init"},
                {"id": 8790},
                {"id": 8797},
                {"id": 8780},
                {"id": 8590},
                {"id": 8597},
                {"id": 8603},
                {"id": 8610},
                {"id": 8765},
                {"id": 8774},
                {"id": 8784},
                {"id": 8795},
                {"id": 8799},
                {"id": 8806},
                {"id": 8808},
                {"id": 8813},
                {"id": 8818},
                {"id": 8821},
                {"id": 8823},
                {"id": 8825},
                {"id": 8830},
                {"id": 8833},
                {"id": 8837},
                {"id": 8840},
            ],
            "links": [
                {
                    "def_info": "input color-5 *(rax)_init",
                    "use_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8787,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "dl",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8797,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "edx",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8806,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "cl",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8808,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ecx",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8818,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "eax",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8821,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "edx",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8823,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "eax",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8825,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ecx",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8825,
                    "key": 1,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8590,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8593,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8597,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8600,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8603,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8610,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8765,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8774,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8780,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8830,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8833,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8837,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8840,
                    "key": 0,
                },
                {
                    "def_info": "input color-1 rsp_init",
                    "use_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rsp",
                        "color": 1,
                    },
                    "color": 1,
                    "source": "input color-1 rsp_init",
                    "target": 8589,
                    "key": 0,
                },
                {
                    "def_info": "input color-3 rdi_init",
                    "use_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8593,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rbp",
                        "index": "None",
                        "scale": 1,
                        "offset": -24,
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8780,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rax",
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8784,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rax",
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8787,
                    "key": 0,
                },
                {
                    "def_info": "input color-4 edx_init",
                    "use_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "edx",
                        "color": 4,
                    },
                    "color": 4,
                    "source": "input color-4 edx_init",
                    "target": 8600,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "ecx",
                        "color": 6,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ecx",
                        "color": 6,
                    },
                    "color": 6,
                    "source": 8790,
                    "target": 8795,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "ecx",
                        "color": 6,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "al",
                        "color": 6,
                    },
                    "color": 6,
                    "source": 8790,
                    "target": 8797,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "ax",
                        "color": 7,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ax",
                        "color": 7,
                    },
                    "color": 7,
                    "source": 8797,
                    "target": 8799,
                    "key": 0,
                },
            ],
        },
    )

    res3 = defusegh == defuseg_hint_truth
    print(f"Def-use graph match: {res3}")

    res = res1 and res2 and res3
    print(f"Test result: passed={res}")
