from colorizer_test import test

from smallworld.hinting.hints import (
    DefUseGraphHint,
    DynamicMemoryValueSummaryHint,
    DynamicRegisterValueSummaryHint
)

if __name__ == "__main__":
    # test(num_insn, buflen, create_heap, fortytwos, randomize_regs, seed):
    hints = test(10, 52, 12, True, 1234)

    summh = [
        h
        for h in hints
        if type(h)
        in set([DynamicMemoryValueSummaryHint, DynamicRegisterValueSummaryHint])
    ]

    # put them in a canonical order by their string repr
    def cmpf(h):
        return (h.pc, str(type(h)), h.message, str(h))

    summh.sort(key=cmpf)

    summary_hints_truth = [
        DynamicRegisterValueSummaryHint(
            message="read-def-summary",
            pc=8589,
            color=1,
            size=8,
            use=True,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="rsp",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8589,
            color=2,
            size=8,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="rsp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8590,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rsp",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8590,
            color=2,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicMemoryValueSummaryHint(
            message="write-copy-summary",
            pc=8593,
            color=3,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            base="rbp",
            index="None",
            scale=1,
            offset=-24,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-def-summary",
            pc=8593,
            color=3,
            size=8,
            use=True,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="rdi",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8593,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8597,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicMemoryValueSummaryHint(
            message="write-copy-summary",
            pc=8600,
            color=4,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            base="rbp",
            index="None",
            scale=1,
            offset=-32,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-def-summary",
            pc=8600,
            color=4,
            size=4,
            use=True,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="edx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8600,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8603,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8610,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicMemoryValueSummaryHint(
            message="read-flow-summary",
            pc=8620,
            color=4,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            base="rbp",
            index="None",
            scale=1,
            offset=-32,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8620,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8626,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8631,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8634,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8643,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicMemoryValueSummaryHint(
            message="read-flow-summary",
            pc=8649,
            color=3,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            base="rbp",
            index="None",
            scale=1,
            offset=-24,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8649,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8649,
            color=3,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8653,
            color=3,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8653,
            color=3,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicMemoryValueSummaryHint(
            message="read-def-summary",
            pc=8656,
            color=5,
            size=1,
            use=True,
            new=True,
            count=10,
            num_micro_executions=10,
            base="rax",
            index="None",
            scale=1,
            offset=0,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8656,
            color=3,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8656,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="edx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8659,
            color=6,
            size=4,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8664,
            color=6,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8664,
            color=6,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8666,
            color=5,
            size=1,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="dl",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8666,
            color=6,
            size=1,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="al",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8666,
            color=7,
            size=1,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="al",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8666,
            color=8,
            size=2,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="ax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8668,
            color=8,
            size=2,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8668,
            color=9,
            size=2,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="ax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8672,
            color=5,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="edx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8672,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8674,
            color=5,
            size=1,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="cl",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8674,
            color=10,
            size=1,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="cl",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8677,
            color=10,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8677,
            color=9,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8677,
            color=11,
            size=4,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8679,
            color=11,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8679,
            color=11,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8681,
            color=11,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8681,
            color=12,
            size=4,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8683,
            color=11,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8683,
            color=12,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8683,
            color=13,
            size=4,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8685,
            color=5,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="edx",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8685,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8687,
            color=13,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="ecx",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8687,
            color=5,
            size=4,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-def-summary",
            pc=8687,
            color=14,
            size=4,
            use=False,
            new=True,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8689,
            color=14,
            size=1,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="al",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8707,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8721,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8724,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicMemoryValueSummaryHint(
            message="read-flow-summary",
            pc=8730,
            color=3,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            base="rbp",
            index="None",
            scale=1,
            offset=-24,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8730,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8730,
            color=3,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8734,
            color=3,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8734,
            color=3,
            size=8,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicMemoryValueSummaryHint(
            message="read-flow-summary",
            pc=8737,
            color=5,
            size=1,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            base="rax",
            index="None",
            scale=1,
            offset=0,
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8737,
            color=3,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rax",
        ),
        DynamicRegisterValueSummaryHint(
            message="write-copy-summary",
            pc=8737,
            color=5,
            size=4,
            use=False,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="eax",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8740,
            color=5,
            size=1,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="al",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8755,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
        DynamicRegisterValueSummaryHint(
            message="read-flow-summary",
            pc=8758,
            color=2,
            size=8,
            use=True,
            new=False,
            count=10,
            num_micro_executions=10,
            reg_name="rbp",
        ),
    ]

    res1 = summh == summary_hints_truth
    print(f"Summary hints match: {res1}")

    defuseghl = [h for h in hints if type(h) is DefUseGraphHint]

    res2 = len(defuseghl) == 1
    print(f"Got a single def-use graph: {res2}")

    defusegh = defuseghl[0]

    defuseg_hint_truth = DefUseGraphHint(
        message="concrete-summary-def-use-graph",
        graph={
            "directed": True,
            "multigraph": True,
            "graph": {},
            "nodes": [
                {"id": 8656},
                {"id": "input color-5 *(rax)_init"},
                {"id": 8589},
                {"id": "input color-1 rsp_init"},
                {"id": 8593},
                {"id": "input color-3 rdi_init"},
                {"id": 8600},
                {"id": "input color-4 edx_init"},
                {"id": 8659},
                {"id": 8666},
                {"id": 8668},
                {"id": 8674},
                {"id": 8677},
                {"id": 8681},
                {"id": 8683},
                {"id": 8687},
                {"id": 8620},
                {"id": 8649},
                {"id": 8730},
                {"id": 8737},
                {"id": 8590},
                {"id": 8597},
                {"id": 8603},
                {"id": 8610},
                {"id": 8626},
                {"id": 8631},
                {"id": 8634},
                {"id": 8643},
                {"id": 8653},
                {"id": 8664},
                {"id": 8672},
                {"id": 8679},
                {"id": 8685},
                {"id": 8689},
                {"id": 8707},
                {"id": 8721},
                {"id": 8724},
                {"id": 8734},
                {"id": 8740},
                {"id": 8755},
                {"id": 8758},
            ],
            "links": [
                {
                    "def_info": "input color-5 *(rax)_init",
                    "use_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8656,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8737,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "dl",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8666,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "edx",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8672,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "cl",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8674,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "edx",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8685,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "eax",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8687,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rax",
                        "index": "None",
                        "scale": 1,
                        "offset": 0,
                        "color": 5,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "al",
                        "color": 5,
                    },
                    "color": 5,
                    "source": "input color-5 *(rax)_init",
                    "target": 8740,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8590,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8593,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8597,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8600,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8603,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8610,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8620,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8626,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8631,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8634,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8643,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8649,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8707,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8721,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8724,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8730,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8755,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "rsp",
                        "color": 2,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rbp",
                        "color": 2,
                    },
                    "color": 2,
                    "source": 8589,
                    "target": 8758,
                    "key": 0,
                },
                {
                    "def_info": "input color-1 rsp_init",
                    "use_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rsp",
                        "color": 1,
                    },
                    "color": 1,
                    "source": "input color-1 rsp_init",
                    "target": 8589,
                    "key": 0,
                },
                {
                    "def_info": "input color-3 rdi_init",
                    "use_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8593,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rbp",
                        "index": "None",
                        "scale": 1,
                        "offset": -24,
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8649,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rbp",
                        "index": "None",
                        "scale": 1,
                        "offset": -24,
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8730,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rax",
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8653,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rax",
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8656,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rax",
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8734,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rdi",
                        "color": 3,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "rax",
                        "color": 3,
                    },
                    "color": 3,
                    "source": "input color-3 rdi_init",
                    "target": 8737,
                    "key": 0,
                },
                {
                    "def_info": "input color-4 edx_init",
                    "use_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "edx",
                        "color": 4,
                    },
                    "color": 4,
                    "source": "input color-4 edx_init",
                    "target": 8600,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "edx",
                        "color": 4,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "mem",
                        "is_read": True,
                        "base": "rbp",
                        "index": "None",
                        "scale": 1,
                        "offset": -32,
                        "color": 4,
                    },
                    "color": 4,
                    "source": "input color-4 edx_init",
                    "target": 8620,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "ecx",
                        "color": 6,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ecx",
                        "color": 6,
                    },
                    "color": 6,
                    "source": 8659,
                    "target": 8664,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "ecx",
                        "color": 6,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "al",
                        "color": 6,
                    },
                    "color": 6,
                    "source": 8659,
                    "target": 8666,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "ax",
                        "color": 8,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ax",
                        "color": 8,
                    },
                    "color": 8,
                    "source": 8666,
                    "target": 8668,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "ax",
                        "color": 9,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "eax",
                        "color": 9,
                    },
                    "color": 9,
                    "source": 8668,
                    "target": 8677,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "cl",
                        "color": 10,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ecx",
                        "color": 10,
                    },
                    "color": 10,
                    "source": 8674,
                    "target": 8677,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "eax",
                        "color": 11,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "eax",
                        "color": 11,
                    },
                    "color": 11,
                    "source": 8677,
                    "target": 8679,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "eax",
                        "color": 11,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ecx",
                        "color": 11,
                    },
                    "color": 11,
                    "source": 8677,
                    "target": 8681,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "eax",
                        "color": 11,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "eax",
                        "color": 11,
                    },
                    "color": 11,
                    "source": 8677,
                    "target": 8683,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "ecx",
                        "color": 12,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ecx",
                        "color": 12,
                    },
                    "color": 12,
                    "source": 8681,
                    "target": 8683,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "ecx",
                        "color": 13,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "ecx",
                        "color": 13,
                    },
                    "color": 13,
                    "source": 8683,
                    "target": 8687,
                    "key": 0,
                },
                {
                    "def_info": {
                        "new": True,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": False,
                        "reg_name": "eax",
                        "color": 14,
                    },
                    "use_info": {
                        "new": False,
                        "count": 10,
                        "num_micro_executions": 10,
                        "type": "reg",
                        "is_read": True,
                        "reg_name": "al",
                        "color": 14,
                    },
                    "color": 14,
                    "source": 8687,
                    "target": 8689,
                    "key": 0,
                },
            ],
        },
    )

    res3 = defusegh == defuseg_hint_truth
    print(f"Def-use graph match: {res3}")

    res = res1 and res2 and res3
    print(f"Test result: passed={res}")
