# type: ignore
from colorizer_test import test

from smallworld.hinting.hints import (
    DefUseGraphHint,
    DynamicMemoryValueSummaryHint,
    DynamicRegisterValueSummaryHint,
    TraceExecutionHint,
)

if __name__ == "__main__":
    # test(num_insn, buflen, create_heap, fortytwos randomize_regs, seed):
    # buflen != 12 but bigger than 0x20
    # so this should *have* derivations back to esi (2nd arg to foo)
    # AND it should reach test against y which derives back to
    hints = test(5, 100, 77, True, 1234)

    # collect all pcs in any trace
    # also tds which is set of digests for a trace
    tds = set([])
    i = 0
    all_pcs = set([])
    for h in hints:
        if type(h) is TraceExecutionHint:
            tds.add(h.trace_digest)
            for te in h.trace:
                all_pcs.add(te.pc)
            i += 1

    num_expected = 0
    num_unexpected = 0

    def expected(cond, msge, msgu):
        global num_expected, num_unexpected
        if cond:
            print(f"EXPECTED  {msge}")
            num_expected += 1
            return True
        else:
            print(f"UNEXPECTED {msgu}")
            num_unexpected += 1
            return False

    truth_all_pcs = {
        8705,
        8707,
        8710,
        8712,
        8585,
        8715,
        8589,
        8590,
        8717,
        8719,
        8593,
        8721,
        8724,
        8597,
        8727,
        8600,
        8730,
        8603,
        8734,
        8737,
        8610,
        8740,
        8614,
        8742,
        8744,
        8620,
        8751,
        8624,
        8626,
        8755,
        8629,
        8758,
        8631,
        8761,
        8634,
        8641,
        8643,
        8646,
        8649,
        8653,
        8656,
        8659,
        8664,
        8666,
        8668,
        8672,
        8674,
        8677,
        8679,
        8681,
        8683,
        8685,
        8687,
        8689,
        8691,
        8693,
        8696,
        8698,
        8700,
        8702,
    }

    expected(
        all_pcs == truth_all_pcs,
        "set of pcs is same for truth and observed",
        "set of pcs disagrees between truth and observed",
    )

    expected(i == 5, "five traces", f"{i} traces")

    expected(len(tds) == 4, "three unique traces", f"{len(tds)} unique traces")

    observed_summ = {}
    for h in hints:
        if type(h) in set(
            [DynamicMemoryValueSummaryHint, DynamicRegisterValueSummaryHint]
        ):
            if h.pc not in observed_summ:
                observed_summ[h.pc] = []
            observed_summ[h.pc].append(h)

    observed_summ_pcs = set(list(observed_summ.keys()))

    truth_summ = {
        8589: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8589,
                color=1,
                size=8,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                base="rsp",
                index="None",
                scale=1,
                offset=0,
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8589,
                color=3,
                size=8,
                use=False,
                new=True,
                count=5,
                num_micro_executions=5,
                reg_name="rsp",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-def-summary",
                pc=8589,
                color=1,
                size=8,
                use=True,
                new=True,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-def-summary",
                pc=8589,
                color=2,
                size=8,
                use=True,
                new=True,
                count=5,
                num_micro_executions=5,
                reg_name="rsp",
            ),
        ],
        8593: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8593,
                color=4,
                size=8,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-24,
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8593,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-def-summary",
                pc=8593,
                color=4,
                size=8,
                use=True,
                new=True,
                count=5,
                num_micro_executions=5,
                reg_name="rdi",
            ),
        ],
        8600: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8600,
                color=5,
                size=4,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-32,
            ),
            DynamicRegisterValueSummaryHint(
                message="read-def-summary",
                pc=8600,
                color=5,
                size=4,
                use=True,
                new=True,
                count=5,
                num_micro_executions=5,
                reg_name="edx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8600,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8620: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8620,
                color=5,
                size=4,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-32,
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8620,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8649: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8649,
                color=4,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-24,
            ),
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8649,
                color=4,
                size=8,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8649,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8656: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8656,
                color=6,
                size=1,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                base="rax",
                index="None",
                scale=1,
                offset=0,
            ),
            DynamicMemoryValueSummaryHint(
                message="read-def-summary",
                pc=8656,
                color=6,
                size=1,
                use=True,
                new=True,
                count=5,
                num_micro_executions=5,
                base="rax",
                index="None",
                scale=1,
                offset=0,
            ),
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8656,
                color=6,
                size=4,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="edx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8656,
                color=4,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rax",
            ),
        ],
        8693: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8693,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-12,
            ),
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8693,
                color=6,
                size=4,
                use=False,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="edx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8693,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8702: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8702,
                color=19,
                size=4,
                use=False,
                new=False,
                count=2,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-12,
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8702,
                color=19,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8702,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8707: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8707,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-12,
            ),
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8707,
                color=6,
                size=4,
                use=False,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8707,
                color=3,
                size=8,
                use=True,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8721: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8721,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-12,
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8721,
                color=17,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8721,
                color=3,
                size=8,
                use=True,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8730: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8730,
                color=4,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-24,
            ),
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8730,
                color=4,
                size=8,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8730,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8737: [
            DynamicMemoryValueSummaryHint(
                message="read-flow-summary",
                pc=8737,
                color=6,
                size=1,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                base="rax",
                index="None",
                scale=1,
                offset=0,
            ),
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8737,
                color=6,
                size=4,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8737,
                color=4,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rax",
            ),
        ],
        8744: [
            DynamicMemoryValueSummaryHint(
                message="write-copy-summary",
                pc=8744,
                color=6,
                size=4,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                base="rbp",
                index="None",
                scale=1,
                offset=-12,
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8744,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
        ],
        8590: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8590,
                color=3,
                size=8,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8590,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rsp",
            ),
        ],
        8597: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8597,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8603: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8603,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8610: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8610,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8626: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8626,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8631: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8631,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8634: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8634,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8643: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8643,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8653: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8653,
                color=4,
                size=8,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rax",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8653,
                color=16,
                size=8,
                use=False,
                new=True,
                count=5,
                num_micro_executions=5,
                reg_name="rax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8653,
                color=4,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rax",
            ),
        ],
        8659: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8659,
                color=7,
                size=4,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8659,
                color=7,
                size=4,
                use=False,
                new=True,
                count=5,
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8664: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8664,
                color=7,
                size=4,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8664,
                color=7,
                size=4,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8666: [
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8666,
                color=8,
                size=1,
                use=False,
                new=True,
                count=3,
                num_micro_executions=5,
                reg_name="al",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8666,
                color=7,
                size=1,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="al",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8666,
                color=6,
                size=1,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="dl",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8666,
                color=9,
                size=2,
                use=False,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="ax",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8666,
                color=9,
                size=2,
                use=False,
                new=True,
                count=5,
                num_micro_executions=5,
                reg_name="ax",
            ),
        ],
        8668: [
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8668,
                color=10,
                size=2,
                use=False,
                new=True,
                count=3,
                num_micro_executions=5,
                reg_name="ax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8668,
                color=9,
                size=2,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="ax",
            ),
        ],
        8672: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8672,
                color=6,
                size=4,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8672,
                color=6,
                size=4,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="edx",
            ),
        ],
        8674: [
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8674,
                color=11,
                size=1,
                use=False,
                new=True,
                count=3,
                num_micro_executions=5,
                reg_name="cl",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8674,
                color=6,
                size=1,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="cl",
            ),
        ],
        8677: [
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8677,
                color=12,
                size=4,
                use=False,
                new=True,
                count=3,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8677,
                color=10,
                size=4,
                use=True,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8677,
                color=11,
                size=4,
                use=True,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8679: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8679,
                color=12,
                size=4,
                use=False,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8679,
                color=12,
                size=4,
                use=True,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="eax",
            ),
        ],
        8681: [
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8681,
                color=13,
                size=4,
                use=False,
                new=True,
                count=3,
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8681,
                color=12,
                size=4,
                use=True,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8683: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8683,
                color=6,
                size=4,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8683,
                color=14,
                size=4,
                use=False,
                new=True,
                count=3,
                num_micro_executions=5,
                reg_name="ecx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8683,
                color=12,
                size=4,
                use=True,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8683,
                color=13,
                size=4,
                use=True,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8685: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8685,
                color=6,
                size=4,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8685,
                color=6,
                size=4,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="edx",
            ),
        ],
        8687: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8687,
                color=11,
                size=4,
                use=False,
                new=False,
                count=1,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8687,
                color=15,
                size=4,
                use=False,
                new=True,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8687,
                color=6,
                size=4,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8687,
                color=14,
                size=4,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="ecx",
            ),
        ],
        8689: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8689,
                color=15,
                size=1,
                use=True,
                new=False,
                count=3,
                num_micro_executions=5,
                reg_name="al",
            )
        ],
        8696: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8696,
                color=6,
                size=4,
                use=False,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8696,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="edx",
            ),
        ],
        8698: [
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8698,
                color=18,
                size=4,
                use=False,
                new=True,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8698,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
        ],
        8700: [
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8700,
                color=19,
                size=4,
                use=False,
                new=True,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8700,
                color=18,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8700,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="edx",
            ),
        ],
        8710: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8710,
                color=6,
                size=4,
                use=False,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="edx",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8710,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
        ],
        8712: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8712,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="edx",
            )
        ],
        8715: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8715,
                color=6,
                size=4,
                use=False,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8715,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            ),
        ],
        8717: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8717,
                color=6,
                size=4,
                use=True,
                new=False,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            )
        ],
        8719: [
            DynamicRegisterValueSummaryHint(
                message="write-def-summary",
                pc=8719,
                color=17,
                size=4,
                use=False,
                new=True,
                count=2,
                num_micro_executions=5,
                reg_name="eax",
            )
        ],
        8724: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8724,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8734: [
            DynamicRegisterValueSummaryHint(
                message="write-copy-summary",
                pc=8734,
                color=4,
                size=8,
                use=False,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rax",
            ),
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8734,
                color=4,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rax",
            ),
        ],
        8740: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8740,
                color=6,
                size=1,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="al",
            )
        ],
        8751: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8751,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8755: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8755,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
        8758: [
            DynamicRegisterValueSummaryHint(
                message="read-flow-summary",
                pc=8758,
                color=3,
                size=8,
                use=True,
                new=False,
                count=5,
                num_micro_executions=5,
                reg_name="rbp",
            )
        ],
    }

    truth_summ_pcs = set(list(truth_summ.keys()))
    expected(
        truth_summ_pcs == observed_summ_pcs,
        "set of pcs observed for summary hints same as truth",
        "pcs observed for summary hints not same as truth",
    )

    for pc in all_pcs:
        if pc in truth_summ_pcs and pc in observed_summ_pcs:
            if not expected(
                observed_summ[pc] == truth_summ[pc],
                f"list of hints observed for pc={pc} same as truth",
                f"list of hints observed for pc={pc} not same as for truth",
            ):
                print(f"Truth:    {truth_summ[pc]}")
                print(f"Observed: {observed_summ[pc]}")
        elif pc in truth_summ_pcs:
            print(f"{truth_summ[pc]} is in truth only")
        elif pc in observed_summ_pcs:
            print(f"{observed_summ[pc]} in observed only")
        else:
            pass

    defuseghl = [h for h in hints if type(h) is DefUseGraphHint]

    res2 = len(defuseghl) == 1
    print(f"Test result: got a single def-use graph = {res2}")

    observed_defuseg = defuseghl[0].graph

    truth_defuseg = {
        "directed": True,
        "multigraph": True,
        "graph": {},
        "nodes": [
            {"id": 8656},
            {"id": "input color-6 *(rax)_init"},
            {"id": 8589},
            {"id": "input color-1 rbp_init"},
            {"id": "input color-2 rsp_init"},
            {"id": 8593},
            {"id": "input color-4 rdi_init"},
            {"id": 8600},
            {"id": "input color-5 edx_init"},
            {"id": 8653},
            {"id": 8659},
            {"id": 8666},
            {"id": 8668},
            {"id": 8674},
            {"id": 8677},
            {"id": 8681},
            {"id": 8683},
            {"id": 8687},
            {"id": 8698},
            {"id": 8700},
            {"id": 8719},
            {"id": 8620},
            {"id": 8649},
            {"id": 8693},
            {"id": 8702},
            {"id": 8707},
            {"id": 8721},
            {"id": 8730},
            {"id": 8737},
            {"id": 8744},
            {"id": 8590},
            {"id": 8597},
            {"id": 8603},
            {"id": 8610},
            {"id": 8626},
            {"id": 8631},
            {"id": 8634},
            {"id": 8643},
            {"id": 8664},
            {"id": 8672},
            {"id": 8679},
            {"id": 8685},
            {"id": 8689},
            {"id": 8696},
            {"id": 8710},
            {"id": 8712},
            {"id": 8715},
            {"id": 8717},
            {"id": 8724},
            {"id": 8734},
            {"id": 8740},
            {"id": 8751},
            {"id": 8755},
            {"id": 8758},
        ],
        "links": [
            {
                "def_info": "input color-6 *(rax)_init",
                "use_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8656,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8656,
                "key": 1,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rbp",
                    "index": "None",
                    "scale": 1,
                    "offset": -12,
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8693,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rbp",
                    "index": "None",
                    "scale": 1,
                    "offset": -12,
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8707,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rbp",
                    "index": "None",
                    "scale": 1,
                    "offset": -12,
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8721,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8737,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "dl",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8666,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "edx",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8672,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "cl",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8674,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "edx",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8685,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8687,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "edx",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8696,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8698,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "edx",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8700,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8710,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "edx",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8712,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8715,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8717,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rax",
                    "index": "None",
                    "scale": 1,
                    "offset": 0,
                    "color": 6,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "al",
                    "color": 6,
                },
                "color": 6,
                "source": "input color-6 *(rax)_init",
                "target": 8740,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8590,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8593,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8597,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8600,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8603,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8610,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8620,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8626,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8631,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8634,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8643,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8649,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8693,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8702,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8707,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8721,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8724,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8730,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8744,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8751,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8755,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "rsp",
                    "color": 3,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 3,
                },
                "color": 3,
                "source": 8589,
                "target": 8758,
                "key": 0,
            },
            {
                "def_info": "input color-1 rbp_init",
                "use_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rbp",
                    "color": 1,
                },
                "color": 1,
                "source": "input color-1 rbp_init",
                "target": 8589,
                "key": 0,
            },
            {
                "def_info": "input color-2 rsp_init",
                "use_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rsp",
                    "color": 2,
                },
                "color": 2,
                "source": "input color-2 rsp_init",
                "target": 8589,
                "key": 0,
            },
            {
                "def_info": "input color-4 rdi_init",
                "use_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rdi",
                    "color": 4,
                },
                "color": 4,
                "source": "input color-4 rdi_init",
                "target": 8593,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rdi",
                    "color": 4,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rbp",
                    "index": "None",
                    "scale": 1,
                    "offset": -24,
                    "color": 4,
                },
                "color": 4,
                "source": "input color-4 rdi_init",
                "target": 8649,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rdi",
                    "color": 4,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rbp",
                    "index": "None",
                    "scale": 1,
                    "offset": -24,
                    "color": 4,
                },
                "color": 4,
                "source": "input color-4 rdi_init",
                "target": 8730,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rdi",
                    "color": 4,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rax",
                    "color": 4,
                },
                "color": 4,
                "source": "input color-4 rdi_init",
                "target": 8653,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rdi",
                    "color": 4,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rax",
                    "color": 4,
                },
                "color": 4,
                "source": "input color-4 rdi_init",
                "target": 8656,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rdi",
                    "color": 4,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rax",
                    "color": 4,
                },
                "color": 4,
                "source": "input color-4 rdi_init",
                "target": 8734,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rdi",
                    "color": 4,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "rax",
                    "color": 4,
                },
                "color": 4,
                "source": "input color-4 rdi_init",
                "target": 8737,
                "key": 0,
            },
            {
                "def_info": "input color-5 edx_init",
                "use_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "edx",
                    "color": 5,
                },
                "color": 5,
                "source": "input color-5 edx_init",
                "target": 8600,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "edx",
                    "color": 5,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "mem",
                    "is_read": True,
                    "base": "rbp",
                    "index": "None",
                    "scale": 1,
                    "offset": -32,
                    "color": 5,
                },
                "color": 5,
                "source": "input color-5 edx_init",
                "target": 8620,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "ecx",
                    "color": 7,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "ecx",
                    "color": 7,
                },
                "color": 7,
                "source": 8659,
                "target": 8664,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "ecx",
                    "color": 7,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "al",
                    "color": 7,
                },
                "color": 7,
                "source": 8659,
                "target": 8666,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "ax",
                    "color": 9,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "ax",
                    "color": 9,
                },
                "color": 9,
                "source": 8666,
                "target": 8668,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "ax",
                    "color": 10,
                },
                "use_info": {
                    "new": False,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 10,
                },
                "color": 10,
                "source": 8668,
                "target": 8677,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "cl",
                    "color": 11,
                },
                "use_info": {
                    "new": False,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "ecx",
                    "color": 11,
                },
                "color": 11,
                "source": 8674,
                "target": 8677,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "eax",
                    "color": 12,
                },
                "use_info": {
                    "new": False,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 12,
                },
                "color": 12,
                "source": 8677,
                "target": 8679,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "eax",
                    "color": 12,
                },
                "use_info": {
                    "new": False,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "ecx",
                    "color": 12,
                },
                "color": 12,
                "source": 8677,
                "target": 8681,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "eax",
                    "color": 12,
                },
                "use_info": {
                    "new": False,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 12,
                },
                "color": 12,
                "source": 8677,
                "target": 8683,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "ecx",
                    "color": 13,
                },
                "use_info": {
                    "new": False,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "ecx",
                    "color": 13,
                },
                "color": 13,
                "source": 8681,
                "target": 8683,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "ecx",
                    "color": 14,
                },
                "use_info": {
                    "new": False,
                    "count": 5,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "ecx",
                    "color": 14,
                },
                "color": 14,
                "source": 8683,
                "target": 8687,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "eax",
                    "color": 15,
                },
                "use_info": {
                    "new": False,
                    "count": 3,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "al",
                    "color": 15,
                },
                "color": 15,
                "source": 8687,
                "target": 8689,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "eax",
                    "color": 18,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 18,
                },
                "color": 18,
                "source": 8698,
                "target": 8700,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "eax",
                    "color": 19,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 19,
                },
                "color": 19,
                "source": 8700,
                "target": 8702,
                "key": 0,
            },
            {
                "def_info": {
                    "new": True,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": False,
                    "reg_name": "eax",
                    "color": 17,
                },
                "use_info": {
                    "new": False,
                    "count": 2,
                    "num_micro_executions": 5,
                    "type": "reg",
                    "is_read": True,
                    "reg_name": "eax",
                    "color": 17,
                },
                "color": 17,
                "source": 8719,
                "target": 8721,
                "key": 0,
            },
        ],
    }

    all_links = []
    for link in observed_defuseg["links"]:
        all_links.append(link)
    for link in truth_defuseg["links"]:
        all_links.append(link)
    for link in all_links:
        expected(
            link in truth_defuseg["links"],
            f"link is in both truth and observed: {link}",
            f"link  is not in truth {link}",
        )
        expected(
            link in observed_defuseg["links"],
            f"link is in both truth and observed: {link}",
            f"link is not in observed {link}",
        )

    expected(
        observed_defuseg == truth_defuseg,
        "the truth and observed def-use graphs agree",
        "the truth and observed def-use graphs differ",
    )

    expected(
        num_unexpected == 0,
        "No unexpected results",
        f"{num_unexpected} unexpected results",
    )
