{
    "code": "../tests/struct.bin",
    "registers": [
        "rax",
        "rdi",
        "rsi",
        "rdx",
        "rcx",
        "r8",
        "r9",
        "r10",
        "r11",
        "rbx",
        "rbp",
        "r12",
        "r13",
        "r14",
        "r15",
        "rip",
        "rsp",
    ],
    "register_info": {
        "rax": "return value",
        "rdi": "1st argument",
        "rsi": "2nd argument",
        "rdx": "3rd argument",
        "rcx": "4th argument",
        "r8": "5th argument",
        "r9": "6th argument",
        "r10": "scratch",
        "r11": "scratch",
        "rbx": "local",
        "rbp": "local",
        "r12": "local",
        "r13": "local",
        "r14": "local",
        "r15": "local",
        "rip": "instruction pointer",
        "rsp": "stack pointer",
    },
    "step": [
        {
            "registers": {
                "rax": None,
                "rdi": None,
                "rsi": None,
                "rdx": None,
                "rcx": None,
                "r8": None,
                "r9": None,
                "r10": None,
                "r11": None,
                "rbx": None,
                "rbp": None,
                "r12": None,
                "r13": None,
                "r14": None,
                "r15": None,
                "rip": 0x11,
                "rsp": 0xFEEDFACEFEEDFACE,
            },
            "highlight_registers": ["rdi"],
            "stack": [None] * 64,
            "hints": [
                {
                    "level": "warn",
                    "message": "Code is mapped to 0, that might cause issues",
                },
                {
                    "level": "alert",
                    "message": "Register RDI is being read, but isn't specified in the environment.",
                },
                {"level": "alert", "message": "Register RDI is a pointer."},
                {
                    "level": "alert",
                    "message": "Whatever RDI is pointing to is at least 24 bytes in size.",
                },
            ],
        }
    ],
}
