import archinfo

from .machdef import AngrMachineDef


class AMD64MachineDef(AngrMachineDef):
    arch = "x86"
    mode = "64"
    byteorder = "little"

    angr_arch = archinfo.arch_amd64.ArchAMD64()

    pc_reg = "rip"

    _registers = {
        "rax": "rax",
        "eax": "eax",
        "ax": "ax",
        "al": "al",
        "ah": "ah",
        "rbx": "rbx",
        "ebx": "ebx",
        "bx": "bx",
        "bl": "bl",
        "bh": "bh",
        "rcx": "rcx",
        "ecx": "ecx",
        "cx": "cx",
        "cl": "cl",
        "ch": "ch",
        "rdx": "rdx",
        "edx": "edx",
        "dx": "dx",
        "dl": "dl",
        "dh": "dh",
        "r8": "r8",
        "r8d": "r8d",
        "r8w": "r8w",
        "r8b": "r8b",
        "r9": "r9",
        "r9d": "r9d",
        "r9w": "r9w",
        "r9b": "r9b",
        "r10": "r10",
        "r10d": "r10d",
        "r10w": "r10w",
        "r10b": "r10b",
        "r11": "r11",
        "r11d": "r11d",
        "r11w": "r11w",
        "r11b": "r11b",
        "r12": "r12",
        "r12d": "r12d",
        "r12w": "r12w",
        "r12b": "r12b",
        "r13": "r13",
        "r13d": "r13d",
        "r13w": "r13w",
        "r13b": "r13b",
        "r14": "r14",
        "r14d": "r14d",
        "r14w": "r14w",
        "r14b": "r14b",
        "r15": "r15",
        "r15d": "r15d",
        "r15w": "r15w",
        "r15b": "r15b",
        "rsi": "rsi",
        "esi": "esi",
        "si": "si",
        "sil": "sil",
        "rdi": "rdi",
        "edi": "edi",
        "di": "di",
        "dil": "dil",
        "rbp": "rbp",
        "ebp": "ebp",
        "bp": "bp",
        "bpl": "bpl",
        "rsp": "rsp",
        "esp": "esp",
        "sp": "sp",
        "spl": "spl",
        "rip": "rip",
        "eip": "eip",
        "ip": "ip",
        "cs": "cs",
        "ds": "ds",
        "es": "es",
        "fs": "fs",
        "gs": "gs",
        "rflags": "rflags",
        "eflags": "eflags",
        "flags": "flags",
        "cr0": "cr0",
        "cr1": "cr1",
        "cr2": "cr2",
        "cr3": "cr3",
        "cr4": "cr4",
    }
