from ..... import platforms
from .....exceptions import ConfigurationError
from ..structs import ElfRela
from .rela import ElfRelocator

# NOTE: This file was auto-generated by an LLM
# Until we have tests for every single ARM relocation type,
# the accuracy of this model is not guaranteed.

# ABI shorthand used in the comments below:
#   A: addend
#   B: base address where the image was loaded
#   G: address of a linker-generated proxy entry, usually in the GOT
#   GOT: base address of the GOT
#   P: address of the relocation field being updated
#   S: resolved symbol value
#   TLSDESC: address of the symbol's TLS descriptor pair
R_AARCH64_NONE = 0  # No relocation; this entry is a marker only.
R_AARCH64_P32_ABS32 = 1  # Write S + A as a 32-bit ILP32 absolute value.
R_AARCH64_P32_COPY = 180  # Copy the symbol's runtime bytes into a 32-bit ILP32 slot.
R_AARCH64_P32_GLOB_DAT = 181  # Populate a 32-bit ILP32 GOT slot with S + A.
R_AARCH64_P32_JUMP_SLOT = (
    182  # Populate a 32-bit ILP32 PLT/GOT resolver slot with S + A.
)
R_AARCH64_P32_RELATIVE = (
    183  # Write B + A into a 32-bit ILP32 slot; ignores the symbol value.
)
R_AARCH64_P32_TLS_DTPMOD = 184  # Write the TLS module ID for ILP32.
R_AARCH64_P32_TLS_DTPREL = 185  # Write the symbol's ILP32 TLS-block-relative offset.
R_AARCH64_P32_TLS_TPREL = (
    186  # Write the symbol's ILP32 thread-pointer-relative TLS offset.
)
R_AARCH64_P32_TLSDESC = 187  # Fill an ILP32 TLS descriptor pair in the GOT.
R_AARCH64_P32_IRELATIVE = 188  # Write the IFUNC resolver result for ILP32.
R_AARCH64_WITHDRAWN = 256  # Withdrawn relocation; treat as R_AARCH64_NONE.
R_AARCH64_ABS64 = 257  # Write S + A as a 64-bit absolute value.
R_AARCH64_ABS32 = 258  # Write S + A as a 32-bit absolute value.
R_AARCH64_ABS16 = 259  # Write S + A as a 16-bit absolute value.
R_AARCH64_PREL64 = 260  # Write S + A - P as a 64-bit PC-relative value.
R_AARCH64_PREL32 = 261  # Write S + A - P as a 32-bit PC-relative value.
R_AARCH64_PREL16 = 262  # Write S + A - P as a 16-bit PC-relative value.
R_AARCH64_MOVW_UABS_G0 = 263  # Encode bits [15:0] of S + A into a MOV{Z,K}.
R_AARCH64_MOVW_UABS_G0_NC = (
    264  # Encode bits [15:0] of S + A into a MOV{Z,K}; no overflow check.
)
R_AARCH64_MOVW_UABS_G1 = 265  # Encode bits [31:16] of S + A into a MOV{Z,K}.
R_AARCH64_MOVW_UABS_G1_NC = (
    266  # Encode bits [31:16] of S + A into a MOV{Z,K}; no overflow check.
)
R_AARCH64_MOVW_UABS_G2 = 267  # Encode bits [47:32] of S + A into a MOV{Z,K}.
R_AARCH64_MOVW_UABS_G2_NC = (
    268  # Encode bits [47:32] of S + A into a MOV{Z,K}; no overflow check.
)
R_AARCH64_MOVW_UABS_G3 = 269  # Encode bits [63:48] of S + A into a MOV{Z,K}.
R_AARCH64_MOVW_SABS_G0 = 270  # Encode bits [15:0] of S + A into a MOV{N,Z}.
R_AARCH64_MOVW_SABS_G1 = 271  # Encode bits [31:16] of S + A into a MOV{N,Z}.
R_AARCH64_MOVW_SABS_G2 = 272  # Encode bits [47:32] of S + A into a MOV{N,Z}.
R_AARCH64_LD_PREL_LO19 = 273  # Encode S + A - P into an LDR literal immediate.
R_AARCH64_ADR_PREL_LO21 = 274  # Encode S + A - P into an ADR immediate.
R_AARCH64_ADR_PREL_PG_HI21 = 275  # Encode Page(S + A) - Page(P) into an ADRP immediate.
R_AARCH64_ADR_PREL_PG_HI21_NC = (
    276  # Encode Page(S + A) - Page(P) into ADRP; no overflow check.
)
R_AARCH64_ADD_ABS_LO12_NC = 277  # Encode bits [11:0] of S + A into an ADD immediate.
R_AARCH64_LDST8_ABS_LO12_NC = (
    278  # Encode bits [11:0] of S + A into an 8-bit LD/ST offset.
)
R_AARCH64_TSTBR14 = 279  # Encode S + A - P into a TBZ/TBNZ immediate.
R_AARCH64_CONDBR19 = 280  # Encode S + A - P into a conditional-branch immediate.
R_AARCH64_JUMP26 = 282  # Encode S + A - P into a B immediate.
R_AARCH64_CALL26 = 283  # Encode S + A - P into a BL immediate.
R_AARCH64_LDST16_ABS_LO12_NC = (
    284  # Encode bits [11:1] of S + A into a 16-bit LD/ST offset.
)
R_AARCH64_LDST32_ABS_LO12_NC = (
    285  # Encode bits [11:2] of S + A into a 32-bit LD/ST offset.
)
R_AARCH64_LDST64_ABS_LO12_NC = (
    286  # Encode bits [11:3] of S + A into a 64-bit LD/ST offset.
)
R_AARCH64_MOVW_PREL_G0 = 287  # Encode bits [15:0] of S + A - P into a MOV{N,Z}.
R_AARCH64_MOVW_PREL_G0_NC = 288  # Encode bits [15:0] of S + A - P into a MOVK.
R_AARCH64_MOVW_PREL_G1 = 289  # Encode bits [31:16] of S + A - P into a MOV{N,Z}.
R_AARCH64_MOVW_PREL_G1_NC = 290  # Encode bits [31:16] of S + A - P into a MOVK.
R_AARCH64_MOVW_PREL_G2 = 291  # Encode bits [47:32] of S + A - P into a MOV{N,Z}.
R_AARCH64_MOVW_PREL_G2_NC = 292  # Encode bits [47:32] of S + A - P into a MOVK.
R_AARCH64_MOVW_PREL_G3 = 293  # Encode bits [63:48] of S + A - P into a MOV{N,Z}.
R_AARCH64_LDST128_ABS_LO12_NC = (
    299  # Encode bits [11:4] of S + A into a 128-bit LD/ST offset.
)
R_AARCH64_MOVW_GOTOFF_G0 = 300  # Encode bits [15:0] of G - GOT into a MOV{N,Z}.
R_AARCH64_MOVW_GOTOFF_G0_NC = 301  # Encode bits [15:0] of G - GOT into a MOVK.
R_AARCH64_MOVW_GOTOFF_G1 = 302  # Encode bits [31:16] of G - GOT into a MOV{N,Z}.
R_AARCH64_MOVW_GOTOFF_G1_NC = 303  # Encode bits [31:16] of G - GOT into a MOVK.
R_AARCH64_MOVW_GOTOFF_G2 = 304  # Encode bits [47:32] of G - GOT into a MOV{N,Z}.
R_AARCH64_MOVW_GOTOFF_G2_NC = 305  # Encode bits [47:32] of G - GOT into a MOVK.
R_AARCH64_MOVW_GOTOFF_G3 = 306  # Encode bits [63:48] of G - GOT into a MOV{N,Z}.
R_AARCH64_GOTREL64 = 307  # Write S + A - GOT as a 64-bit GOT-relative value.
R_AARCH64_GOTREL32 = 308  # Write S + A - GOT as a 32-bit GOT-relative value.
R_AARCH64_GOT_LD_PREL19 = 309  # Encode G - P into an LDR literal immediate.
R_AARCH64_LD64_GOTOFF_LO15 = 310  # Encode G - GOT into a 64-bit LD/ST offset.
R_AARCH64_ADR_GOT_PAGE = 311  # Encode Page(G) - Page(P) into an ADRP immediate.
R_AARCH64_LD64_GOT_LO12_NC = 312  # Encode bits [11:3] of G into a 64-bit LD/ST offset.
R_AARCH64_LD64_GOTPAGE_LO15 = 313  # Encode G - Page(GOT) into a 64-bit LD/ST offset.
R_AARCH64_PLT32 = 314  # Write S + A - P as a 32-bit code-pointer offset.
R_AARCH64_GOTPCREL32 = 315  # Write G - P + A as a 32-bit GOT-entry-relative value.
R_AARCH64_PATCHINST = 316  # Write S + A as a patched 32-bit instruction word.
R_AARCH64_FUNCINIT64 = 317  # Generate a run-time FUNCINIT relocation based on S + A.
R_AARCH64_TLSGD_ADR_PREL21 = 512  # Encode GTLSIDX(S) - P into an ADR immediate.
R_AARCH64_TLSGD_ADR_PAGE21 = 513  # Encode Page(GTLSIDX(S)) - Page(P) into ADRP.
R_AARCH64_TLSGD_ADD_LO12_NC = 514  # Encode bits [11:0] of GTLSIDX(S) into ADD.
R_AARCH64_TLSGD_MOVW_G1 = 515  # Encode bits [31:16] of GTLSIDX(S) - GOT into MOV{N,Z}.
R_AARCH64_TLSGD_MOVW_G0_NC = 516  # Encode bits [15:0] of GTLSIDX(S) - GOT into MOVK.
R_AARCH64_TLSLD_ADR_PREL21 = 517  # Encode GLDM(S) - P into an ADR immediate.
R_AARCH64_TLSLD_ADR_PAGE21 = 518  # Encode Page(GLDM(S)) - Page(P) into ADRP.
R_AARCH64_TLSLD_ADD_LO12_NC = 519  # Encode bits [11:0] of GLDM(S) into ADD.
R_AARCH64_TLSLD_MOVW_G1 = 520  # Encode bits [31:16] of GLDM(S) - GOT into MOV{N,Z}.
R_AARCH64_TLSLD_MOVW_G0_NC = 521  # Encode bits [15:0] of GLDM(S) - GOT into MOVK.
R_AARCH64_TLSLD_LD_PREL19 = 522  # Encode GLDM(S) - P into an LDR literal immediate.
R_AARCH64_TLSLD_MOVW_DTPREL_G2 = (
    523  # Encode bits [47:32] of DTPREL(S + A) into MOV{N,Z}.
)
R_AARCH64_TLSLD_MOVW_DTPREL_G1 = (
    524  # Encode bits [31:16] of DTPREL(S + A) into MOV{N,Z}.
)
R_AARCH64_TLSLD_MOVW_DTPREL_G1_NC = (
    525  # Encode bits [31:16] of DTPREL(S + A) into MOVK.
)
R_AARCH64_TLSLD_MOVW_DTPREL_G0 = (
    526  # Encode bits [15:0] of DTPREL(S + A) into MOV{N,Z}.
)
R_AARCH64_TLSLD_MOVW_DTPREL_G0_NC = (
    527  # Encode bits [15:0] of DTPREL(S + A) into MOVK.
)
R_AARCH64_TLSLD_ADD_DTPREL_HI12 = 528  # Encode bits [23:12] of DTPREL(S + A) into ADD.
R_AARCH64_TLSLD_ADD_DTPREL_LO12 = 529  # Encode bits [11:0] of DTPREL(S + A) into ADD.
R_AARCH64_TLSLD_ADD_DTPREL_LO12_NC = (
    530  # Encode bits [11:0] of DTPREL(S + A) into ADD; no overflow check.
)
R_AARCH64_TLSLD_LDST8_DTPREL_LO12 = (
    531  # Encode bits [11:0] of DTPREL(S + A) into an 8-bit LD/ST offset.
)
R_AARCH64_TLSLD_LDST8_DTPREL_LO12_NC = 532  # Encode bits [11:0] of DTPREL(S + A) into an 8-bit LD/ST offset; no overflow check.
R_AARCH64_TLSLD_LDST16_DTPREL_LO12 = (
    533  # Encode bits [11:1] of DTPREL(S + A) into a 16-bit LD/ST offset.
)
R_AARCH64_TLSLD_LDST16_DTPREL_LO12_NC = 534  # Encode bits [11:1] of DTPREL(S + A) into a 16-bit LD/ST offset; no overflow check.
R_AARCH64_TLSLD_LDST32_DTPREL_LO12 = (
    535  # Encode bits [11:2] of DTPREL(S + A) into a 32-bit LD/ST offset.
)
R_AARCH64_TLSLD_LDST32_DTPREL_LO12_NC = 536  # Encode bits [11:2] of DTPREL(S + A) into a 32-bit LD/ST offset; no overflow check.
R_AARCH64_TLSLD_LDST64_DTPREL_LO12 = (
    537  # Encode bits [11:3] of DTPREL(S + A) into a 64-bit LD/ST offset.
)
R_AARCH64_TLSLD_LDST64_DTPREL_LO12_NC = 538  # Encode bits [11:3] of DTPREL(S + A) into a 64-bit LD/ST offset; no overflow check.
R_AARCH64_TLSIE_MOVW_GOTTPREL_G1 = (
    539  # Encode bits [31:16] of GTPREL(S) - GOT into MOV{N,Z}.
)
R_AARCH64_TLSIE_MOVW_GOTTPREL_G0_NC = (
    540  # Encode bits [15:0] of GTPREL(S) - GOT into MOVK.
)
R_AARCH64_TLSIE_ADR_GOTTPREL_PAGE21 = 541  # Encode Page(GTPREL(S)) - Page(P) into ADRP.
R_AARCH64_TLSIE_LD64_GOTTPREL_LO12_NC = (
    542  # Encode bits [11:3] of GTPREL(S) into a 64-bit LD/ST offset.
)
R_AARCH64_TLSIE_LD_GOTTPREL_PREL19 = (
    543  # Encode GTPREL(S) - P into an LDR literal immediate.
)
R_AARCH64_TLSLE_MOVW_TPREL_G2 = (
    544  # Encode bits [47:32] of TPREL(S + A) into MOV{N,Z}.
)
R_AARCH64_TLSLE_MOVW_TPREL_G1 = (
    545  # Encode bits [31:16] of TPREL(S + A) into MOV{N,Z}.
)
R_AARCH64_TLSLE_MOVW_TPREL_G1_NC = 546  # Encode bits [31:16] of TPREL(S + A) into MOVK.
R_AARCH64_TLSLE_MOVW_TPREL_G0 = 547  # Encode bits [15:0] of TPREL(S + A) into MOV{N,Z}.
R_AARCH64_TLSLE_MOVW_TPREL_G0_NC = 548  # Encode bits [15:0] of TPREL(S + A) into MOVK.
R_AARCH64_TLSLE_ADD_TPREL_HI12 = 549  # Encode bits [23:12] of TPREL(S + A) into ADD.
R_AARCH64_TLSLE_ADD_TPREL_LO12 = 550  # Encode bits [11:0] of TPREL(S + A) into ADD.
R_AARCH64_TLSLE_ADD_TPREL_LO12_NC = (
    551  # Encode bits [11:0] of TPREL(S + A) into ADD; no overflow check.
)
R_AARCH64_TLSLE_LDST8_TPREL_LO12 = (
    552  # Encode bits [11:0] of TPREL(S + A) into an 8-bit LD/ST offset.
)
R_AARCH64_TLSLE_LDST8_TPREL_LO12_NC = 553  # Encode bits [11:0] of TPREL(S + A) into an 8-bit LD/ST offset; no overflow check.
R_AARCH64_TLSLE_LDST16_TPREL_LO12 = (
    554  # Encode bits [11:1] of TPREL(S + A) into a 16-bit LD/ST offset.
)
R_AARCH64_TLSLE_LDST16_TPREL_LO12_NC = 555  # Encode bits [11:1] of TPREL(S + A) into a 16-bit LD/ST offset; no overflow check.
R_AARCH64_TLSLE_LDST32_TPREL_LO12 = (
    556  # Encode bits [11:2] of TPREL(S + A) into a 32-bit LD/ST offset.
)
R_AARCH64_TLSLE_LDST32_TPREL_LO12_NC = 557  # Encode bits [11:2] of TPREL(S + A) into a 32-bit LD/ST offset; no overflow check.
R_AARCH64_TLSLE_LDST64_TPREL_LO12 = (
    558  # Encode bits [11:3] of TPREL(S + A) into a 64-bit LD/ST offset.
)
R_AARCH64_TLSLE_LDST64_TPREL_LO12_NC = 559  # Encode bits [11:3] of TPREL(S + A) into a 64-bit LD/ST offset; no overflow check.
R_AARCH64_TLSDESC_LD_PREL19 = 560  # Encode TLSDESC - P into an LDR literal immediate.
R_AARCH64_TLSDESC_ADR_PREL21 = 561  # Encode TLSDESC - P into an ADR immediate.
R_AARCH64_TLSDESC_ADR_PAGE21 = 562  # Encode Page(TLSDESC) - Page(P) into ADRP.
R_AARCH64_TLSDESC_LD64_LO12 = (
    563  # Encode bits [11:3] of TLSDESC into a 64-bit LD offset.
)
R_AARCH64_TLSDESC_ADD_LO12 = 564  # Encode bits [11:0] of TLSDESC into an ADD immediate.
R_AARCH64_TLSDESC_OFF_G1 = 565  # Encode bits [31:16] of TLSDESC - GOT into MOV{N,Z}.
R_AARCH64_TLSDESC_OFF_G0_NC = 566  # Encode bits [15:0] of TLSDESC - GOT into MOVK.
R_AARCH64_TLSDESC_LDR = 567  # Relaxation marker for the TLS descriptor load.
R_AARCH64_TLSDESC_ADD = (
    568  # Relaxation marker for the TLS descriptor address computation.
)
R_AARCH64_TLSDESC_CALL = 569  # Relaxation marker for the TLS descriptor BLR call.
R_AARCH64_TLSLE_LDST128_TPREL_LO12 = (
    570  # Encode bits [11:4] of TPREL(S + A) into a 128-bit LD/ST offset.
)
R_AARCH64_TLSLE_LDST128_TPREL_LO12_NC = 571  # Encode bits [11:4] of TPREL(S + A) into a 128-bit LD/ST offset; no overflow check.
R_AARCH64_TLSLD_LDST128_DTPREL_LO12 = (
    572  # Encode bits [11:4] of DTPREL(S + A) into a 128-bit LD/ST offset.
)
R_AARCH64_TLSLD_LDST128_DTPREL_LO12_NC = 573  # Encode bits [11:4] of DTPREL(S + A) into a 128-bit LD/ST offset; no overflow check.
R_AARCH64_AUTH_ABS64 = 580  # Pointer-authenticated ABS64 relocation.
R_AARCH64_AUTH_MOVW_GOTOFF_G0 = 581  # Encode bits [15:0] of the authenticated proxy address minus GOT into MOV{N,Z}.
R_AARCH64_AUTH_MOVW_GOTOFF_G0_NC = (
    582  # Encode bits [15:0] of the authenticated proxy address minus GOT into MOVK.
)
R_AARCH64_AUTH_MOVW_GOTOFF_G1 = 583  # Encode bits [31:16] of the authenticated proxy address minus GOT into MOV{N,Z}.
R_AARCH64_AUTH_MOVW_GOTOFF_G1_NC = (
    584  # Encode bits [31:16] of the authenticated proxy address minus GOT into MOVK.
)
R_AARCH64_AUTH_MOVW_GOTOFF_G2 = 585  # Encode bits [47:32] of the authenticated proxy address minus GOT into MOV{N,Z}.
R_AARCH64_AUTH_MOVW_GOTOFF_G2_NC = (
    586  # Encode bits [47:32] of the authenticated proxy address minus GOT into MOVK.
)
R_AARCH64_AUTH_MOVW_GOTOFF_G3 = 587  # Encode bits [63:48] of the authenticated proxy address minus GOT into MOV{N,Z}.
R_AARCH64_AUTH_GOT_LD_PREL19 = (
    588  # Encode the authenticated proxy address minus P into an LDR literal immediate.
)
R_AARCH64_AUTH_LD64_GOTOFF_LO15 = (
    589  # Encode the authenticated proxy address minus GOT into a 64-bit LD/ST offset.
)
R_AARCH64_AUTH_ADR_GOT_PAGE = (
    590  # Encode Page(authenticated proxy) - Page(P) into ADRP.
)
R_AARCH64_AUTH_LD64_GOT_LO12_NC = 591  # Encode bits [11:3] of the authenticated proxy address into a 64-bit LD/ST offset.
R_AARCH64_AUTH_LD64_GOTPAGE_LO15 = 592  # Encode the authenticated proxy address minus Page(GOT) into a 64-bit LD/ST offset.
R_AARCH64_AUTH_GOT_ADD_LO12_NC = (
    593  # Encode bits [11:0] of the authenticated proxy address into ADD.
)
R_AARCH64_AUTH_GOT_ADR_PREL_LO21 = (
    594  # Encode the authenticated proxy address minus P into ADR.
)
R_AARCH64_AUTH_TLSDESC_ADR_PAGE21 = (
    595  # Encode Page(authenticated TLSDESC) - Page(P) into ADRP.
)
R_AARCH64_AUTH_TLSDESC_LD64_LO12 = (
    596  # Encode bits [11:3] of the authenticated TLSDESC address into LD.
)
R_AARCH64_AUTH_TLSDESC_ADD_LO12 = (
    597  # Encode bits [11:0] of the authenticated TLSDESC address into ADD.
)
R_AARCH64_COPY = 1024  # Copy the symbol's runtime bytes into the relocation target.
R_AARCH64_GLOB_DAT = 1025  # Populate a GOT slot with S + A.
R_AARCH64_JUMP_SLOT = 1026  # Populate a PLT/GOT resolver slot with S + A.
R_AARCH64_RELATIVE = 1027  # Write B + A; ignores the symbol value.
R_AARCH64_TLS_DTPMOD = 1028  # Write the TLS module ID containing the symbol.
R_AARCH64_TLS_DTPREL = 1029  # Write the symbol's offset within its TLS block.
R_AARCH64_TLS_TPREL = 1030  # Write the symbol's thread-pointer-relative TLS offset.
R_AARCH64_TLSDESC = 1031  # Fill a TLS descriptor pair in the GOT.
R_AARCH64_IRELATIVE = 1032  # Write the value returned by an IFUNC resolver at B + A.
R_AARCH64_AUTH_RELATIVE = 1041  # Pointer-authenticated RELATIVE relocation.
R_AARCH64_AUTH_GLOB_DAT = (
    1042  # Populate an authenticated GOT slot with a signed S + A.
)
R_AARCH64_AUTH_TLSDESC = 1043  # Fill an authenticated TLS descriptor pair in the GOT.
R_AARCH64_AUTH_IRELATIVE = 1044  # Pointer-authenticated IFUNC relocation.

DT_PLTGOT = 3  # Dynamic tag for the GOT base address.
MOVW_OP_MOVN = 0
MOVW_OP_MOVZ = 2


class AArch64ElfRelocator(ElfRelocator):
    arch = platforms.Architecture.AARCH64
    byteorder = platforms.Byteorder.LITTLE

    def _symbol_name(self, rela: ElfRela) -> str:
        return rela.symbol.name if rela.symbol.name else "<anonymous>"

    def _symbol_value(self, rela: ElfRela) -> int:
        return rela.symbol.value + rela.symbol.baseaddr

    def _word_size(self, elf) -> int:
        lief_elf = getattr(elf, "_elf", None)
        if lief_elf is not None and lief_elf.header.identity_class.value == 1:
            return 4
        return 8

    def _get_data_addend(self, rela: ElfRela, elf, size: int) -> int:
        if rela.is_rela:
            return rela.addend
        return int.from_bytes(
            elf.read_bytes(rela.offset, size), self.byteorder.value, signed=True
        )

    def _get_rela_addend(self, rela: ElfRela) -> int:
        if rela.is_rela:
            return rela.addend

        # AArch64 supports REL relocations, but recovering a general addend from
        # instruction encodings requires relocation-specific decoding and, for
        # grouped instructions, knowledge of the surrounding relocation sequence.
        raise ConfigurationError(
            f"Relocation {hex(rela.type)} for {self._symbol_name(rela)} requires "
            f"an explicit RELA addend; extracting embedded addends from AArch64 "
            f"REL instruction encodings is not implemented"
        )

    def _pack(self, value: int, size: int) -> bytes:
        mask = (1 << (size * 8)) - 1
        return (value & mask).to_bytes(size, self.byteorder.value)

    def _pack_insn(self, value: int) -> bytes:
        return (value & 0xFFFFFFFF).to_bytes(4, self.byteorder.value)

    def _read_insn(self, rela: ElfRela, elf) -> int:
        return elf.read_int(rela.offset, 4, self.byteorder)

    def _check_range(
        self, value: int, lower: int, upper: int, rela: ElfRela, detail: str
    ) -> None:
        if not (lower <= value < upper):
            raise ConfigurationError(
                f"Relocation {hex(rela.type)} for {self._symbol_name(rela)} "
                f"overflowed {detail}: {value}"
            )

    def _check_aligned(
        self, value: int, alignment: int, rela: ElfRela, detail: str
    ) -> None:
        if value % alignment != 0:
            raise ConfigurationError(
                f"Relocation {hex(rela.type)} for {self._symbol_name(rela)} "
                f"requires {detail} aligned to {alignment} bytes, got {value}"
            )

    def _page(self, value: int) -> int:
        return value & ~0xFFF

    def _missing_context(self, rela: ElfRela, detail: str) -> None:
        raise ConfigurationError(
            f"Relocation {hex(rela.type)} for {self._symbol_name(rela)} requires "
            f"{detail}, which is not available to AArch64ElfRelocator._compute_value()"
        )

    def _patch_mov_imm16(self, orig: int, imm16: int, movop=None) -> int:
        patched = (orig & ~(0xFFFF << 5)) | ((imm16 & 0xFFFF) << 5)
        if movop is not None:
            patched = (patched & ~(0b11 << 29)) | ((movop & 0b11) << 29)
        return patched

    def _patch_imm19(self, orig: int, value: int) -> int:
        imm19 = (value >> 2) & 0x7FFFF
        return (orig & ~(0x7FFFF << 5)) | (imm19 << 5)

    def _patch_tbz_imm14(self, orig: int, value: int) -> int:
        imm14 = (value >> 2) & 0x3FFF
        return (orig & ~(0x3FFF << 5)) | (imm14 << 5)

    def _patch_adr_imm21(self, orig: int, value: int, page: bool = False) -> int:
        if page:
            value >>= 12
        imm21 = value & 0x1FFFFF
        patched = orig & ~((0x3 << 29) | (0x7FFFF << 5))
        patched |= (imm21 & 0x3) << 29
        patched |= ((imm21 >> 2) & 0x7FFFF) << 5
        return patched

    def _patch_branch26(self, orig: int, value: int) -> int:
        imm26 = (value >> 2) & 0x3FFFFFF
        return (orig & ~0x3FFFFFF) | imm26

    def _patch_add_imm12(self, orig: int, value: int, shift12: bool) -> int:
        imm12 = ((value >> 12) if shift12 else value) & 0xFFF
        patched = orig & ~((1 << 22) | (0xFFF << 10))
        if shift12:
            patched |= 1 << 22
        patched |= imm12 << 10
        return patched

    def _patch_ldst_uimm12(self, orig: int, value: int, scale: int) -> int:
        imm12 = (value >> scale) & 0xFFF
        return (orig & ~(0xFFF << 10)) | (imm12 << 10)

    def _apply_mov_unsigned(
        self, rela: ElfRela, elf, value: int, shift: int, check_bits=None
    ) -> bytes:
        if check_bits is not None:
            self._check_range(
                value,
                0,
                1 << check_bits,
                rela,
                f"{check_bits}-bit unsigned MOVW relocation",
            )
        orig = self._read_insn(rela, elf)
        imm16 = (value >> shift) & 0xFFFF
        return self._pack_insn(self._patch_mov_imm16(orig, imm16))

    def _apply_mov_signed(
        self,
        rela: ElfRela,
        elf,
        value: int,
        shift: int,
        check_bits=None,
        movk: bool = False,
    ) -> bytes:
        if check_bits is not None:
            self._check_range(
                value,
                -(1 << check_bits),
                1 << check_bits,
                rela,
                f"{check_bits}-bit signed MOVW relocation",
            )

        orig = self._read_insn(rela, elf)
        if movk:
            imm16 = (value >> shift) & 0xFFFF
            return self._pack_insn(self._patch_mov_imm16(orig, imm16))

        if value >= 0:
            imm16 = (value >> shift) & 0xFFFF
            return self._pack_insn(
                self._patch_mov_imm16(orig, imm16, movop=MOVW_OP_MOVZ)
            )

        imm16 = (~((value >> shift) & 0xFFFF)) & 0xFFFF
        return self._pack_insn(self._patch_mov_imm16(orig, imm16, movop=MOVW_OP_MOVN))

    def _got_base(self, rela: ElfRela, elf) -> int:
        dtags = getattr(elf, "_dtags", {})
        if DT_PLTGOT in dtags:
            return elf._rebase_file(dtags[DT_PLTGOT])

        lief_elf = getattr(elf, "_elf", None)
        section_offsets = getattr(elf, "_section_offsets", {})
        if lief_elf is not None:
            for name in (".got.plt", ".got"):
                for idx, section in enumerate(lief_elf.sections):
                    if section.name != name:
                        continue
                    if getattr(section, "virtual_address", 0):
                        return elf._rebase_file(section.virtual_address)
                    if idx in section_offsets:
                        return elf.address + section_offsets[idx]

        self._missing_context(rela, "the GOT base address")
        raise Exception("Reached an unreachable line")

    def _proxy_offset(self, rela: ElfRela, proxy_types, detail: str) -> int:
        offsets = sorted({r.offset for r in rela.symbol.relas if r.type in proxy_types})
        if len(offsets) == 1:
            return offsets[0]
        if len(offsets) == 0:
            self._missing_context(rela, detail)

        raise ConfigurationError(
            f"Relocation {hex(rela.type)} for {self._symbol_name(rela)} has "
            f"multiple candidate proxy entries for {detail}: "
            f"{', '.join(map(hex, offsets))}"
        )

    def _tls_pair_base(self, rela: ElfRela, elf, proxy_types, detail: str) -> int:
        offsets = sorted({r.offset for r in rela.symbol.relas if r.type in proxy_types})
        if len(offsets) == 1:
            return offsets[0]
        if len(offsets) == 2 and offsets[1] - offsets[0] == self._word_size(elf):
            return offsets[0]
        if len(offsets) == 0:
            self._missing_context(rela, detail)

        raise ConfigurationError(
            f"Relocation {hex(rela.type)} for {self._symbol_name(rela)} has "
            f"ambiguous TLS proxy entries for {detail}: "
            f"{', '.join(map(hex, offsets))}"
        )

    def _compute_value(self, rela: ElfRela, elf):
        symval = self._symbol_value(rela)

        if rela.type == R_AARCH64_NONE or rela.type == R_AARCH64_WITHDRAWN:
            return b""

        elif rela.type == R_AARCH64_P32_ABS32:
            value = symval + self._get_data_addend(rela, elf, 4)
            self._check_range(value, -(1 << 31), 1 << 32, rela, "32-bit P32_ABS32")
            return self._pack(value, 4)
        elif rela.type == R_AARCH64_P32_GLOB_DAT:
            value = symval + self._get_data_addend(rela, elf, 4)
            self._check_range(value, -(1 << 31), 1 << 32, rela, "32-bit P32_GLOB_DAT")
            return self._pack(value, 4)
        elif rela.type == R_AARCH64_P32_JUMP_SLOT:
            addend = rela.addend if rela.is_rela else 0
            value = symval + addend
            self._check_range(value, -(1 << 31), 1 << 32, rela, "32-bit P32_JUMP_SLOT")
            return self._pack(value, 4)
        elif rela.type == R_AARCH64_P32_RELATIVE:
            value = elf.address + self._get_data_addend(rela, elf, 4)
            self._check_range(value, -(1 << 31), 1 << 32, rela, "32-bit P32_RELATIVE")
            return self._pack(value, 4)
        elif rela.type == R_AARCH64_P32_COPY:
            # Copy relocations need the bytes stored at the resolved symbol,
            # not just the symbol's address or size.
            self._missing_context(rela, "the copied symbol's source bytes")
        elif rela.type in (
            R_AARCH64_P32_TLS_DTPMOD,
            R_AARCH64_P32_TLS_DTPREL,
            R_AARCH64_P32_TLS_TPREL,
        ):
            # These relocations need the final layout of the module's TLS block
            # and, for TPREL, the execution environment's thread pointer model.
            self._missing_context(
                rela,
                "the symbol's TLS module ID and/or its final TLS block offset",
            )
        elif rela.type == R_AARCH64_P32_TLSDESC:
            # Filling a TLS descriptor requires the descriptor contents and
            # resolver state, not just the descriptor's address.
            self._missing_context(
                rela,
                "the TLS descriptor contents and resolver state",
            )
        elif rela.type == R_AARCH64_P32_IRELATIVE:
            # Indirect relative relocations require executing an IFUNC resolver
            # at load time and using its return value.
            self._missing_context(rela, "IFUNC resolver execution and its return value")

        elif rela.type == R_AARCH64_ABS64:
            return self._pack(symval + self._get_data_addend(rela, elf, 8), 8)
        elif rela.type == R_AARCH64_ABS32:
            value = symval + self._get_data_addend(rela, elf, 4)
            self._check_range(value, -(1 << 31), 1 << 32, rela, "32-bit ABS32")
            return self._pack(value, 4)
        elif rela.type == R_AARCH64_ABS16:
            value = symval + self._get_data_addend(rela, elf, 2)
            self._check_range(value, -(1 << 15), 1 << 16, rela, "16-bit ABS16")
            return self._pack(value, 2)
        elif rela.type == R_AARCH64_PREL64:
            return self._pack(
                symval + self._get_data_addend(rela, elf, 8) - rela.offset, 8
            )
        elif rela.type == R_AARCH64_PREL32:
            value = symval + self._get_data_addend(rela, elf, 4) - rela.offset
            self._check_range(value, -(1 << 31), 1 << 32, rela, "32-bit PREL32")
            return self._pack(value, 4)
        elif rela.type == R_AARCH64_PREL16:
            value = symval + self._get_data_addend(rela, elf, 2) - rela.offset
            self._check_range(value, -(1 << 15), 1 << 16, rela, "16-bit PREL16")
            return self._pack(value, 2)
        elif rela.type == R_AARCH64_PLT32:
            value = symval + self._get_data_addend(rela, elf, 4) - rela.offset
            self._check_range(value, -(1 << 31), 1 << 31, rela, "32-bit PLT32")
            return self._pack(value, 4)
        elif rela.type == R_AARCH64_GOTREL64:
            return self._pack(
                symval
                + self._get_data_addend(rela, elf, 8)
                - self._got_base(rela, elf),
                8,
            )
        elif rela.type == R_AARCH64_GOTREL32:
            value = (
                symval + self._get_data_addend(rela, elf, 4) - self._got_base(rela, elf)
            )
            self._check_range(value, -(1 << 31), 1 << 31, rela, "32-bit GOTREL32")
            return self._pack(value, 4)
        elif rela.type == R_AARCH64_GOTPCREL32:
            got_entry = self._proxy_offset(
                rela,
                (R_AARCH64_GLOB_DAT, R_AARCH64_AUTH_GLOB_DAT),
                "the symbol's GOT entry address",
            )
            value = got_entry - rela.offset + self._get_data_addend(rela, elf, 4)
            self._check_range(value, -(1 << 31), 1 << 31, rela, "32-bit GOTPCREL32")
            return self._pack(value, 4)
        elif rela.type == R_AARCH64_GLOB_DAT:
            return self._pack(symval + self._get_data_addend(rela, elf, 8), 8)
        elif rela.type == R_AARCH64_JUMP_SLOT:
            addend = rela.addend if rela.is_rela else 0
            return self._pack(symval + addend, 8)
        elif rela.type == R_AARCH64_RELATIVE:
            return self._pack(elf.address + self._get_data_addend(rela, elf, 8), 8)
        elif rela.type == R_AARCH64_COPY:
            # Copy relocations need the bytes stored at the resolved symbol,
            # not just the symbol's address or size.
            self._missing_context(rela, "the copied symbol's source bytes")

        elif rela.type == R_AARCH64_MOVW_UABS_G0:
            return self._apply_mov_unsigned(
                rela, elf, symval + self._get_rela_addend(rela), 0, 16
            )
        elif rela.type == R_AARCH64_MOVW_UABS_G0_NC:
            return self._apply_mov_unsigned(
                rela, elf, symval + self._get_rela_addend(rela), 0
            )
        elif rela.type == R_AARCH64_MOVW_UABS_G1:
            return self._apply_mov_unsigned(
                rela, elf, symval + self._get_rela_addend(rela), 16, 32
            )
        elif rela.type == R_AARCH64_MOVW_UABS_G1_NC:
            return self._apply_mov_unsigned(
                rela, elf, symval + self._get_rela_addend(rela), 16
            )
        elif rela.type == R_AARCH64_MOVW_UABS_G2:
            return self._apply_mov_unsigned(
                rela, elf, symval + self._get_rela_addend(rela), 32, 48
            )
        elif rela.type == R_AARCH64_MOVW_UABS_G2_NC:
            return self._apply_mov_unsigned(
                rela, elf, symval + self._get_rela_addend(rela), 32
            )
        elif rela.type == R_AARCH64_MOVW_UABS_G3:
            return self._apply_mov_unsigned(
                rela, elf, symval + self._get_rela_addend(rela), 48
            )
        elif rela.type == R_AARCH64_MOVW_SABS_G0:
            return self._apply_mov_signed(
                rela, elf, symval + self._get_rela_addend(rela), 0, 16
            )
        elif rela.type == R_AARCH64_MOVW_SABS_G1:
            return self._apply_mov_signed(
                rela, elf, symval + self._get_rela_addend(rela), 16, 32
            )
        elif rela.type == R_AARCH64_MOVW_SABS_G2:
            return self._apply_mov_signed(
                rela, elf, symval + self._get_rela_addend(rela), 32, 48
            )
        elif rela.type == R_AARCH64_MOVW_PREL_G0:
            return self._apply_mov_signed(
                rela,
                elf,
                symval + self._get_rela_addend(rela) - rela.offset,
                0,
                16,
            )
        elif rela.type == R_AARCH64_MOVW_PREL_G0_NC:
            return self._apply_mov_signed(
                rela,
                elf,
                symval + self._get_rela_addend(rela) - rela.offset,
                0,
                movk=True,
            )
        elif rela.type == R_AARCH64_MOVW_PREL_G1:
            return self._apply_mov_signed(
                rela,
                elf,
                symval + self._get_rela_addend(rela) - rela.offset,
                16,
                32,
            )
        elif rela.type == R_AARCH64_MOVW_PREL_G1_NC:
            return self._apply_mov_signed(
                rela,
                elf,
                symval + self._get_rela_addend(rela) - rela.offset,
                16,
                movk=True,
            )
        elif rela.type == R_AARCH64_MOVW_PREL_G2:
            return self._apply_mov_signed(
                rela,
                elf,
                symval + self._get_rela_addend(rela) - rela.offset,
                32,
                48,
            )
        elif rela.type == R_AARCH64_MOVW_PREL_G2_NC:
            return self._apply_mov_signed(
                rela,
                elf,
                symval + self._get_rela_addend(rela) - rela.offset,
                32,
                movk=True,
            )
        elif rela.type == R_AARCH64_MOVW_PREL_G3:
            return self._apply_mov_signed(
                rela,
                elf,
                symval + self._get_rela_addend(rela) - rela.offset,
                48,
            )

        elif rela.type == R_AARCH64_LD_PREL_LO19:
            value = symval + self._get_rela_addend(rela) - rela.offset
            self._check_range(value, -(1 << 20), 1 << 20, rela, "LD_PREL_LO19")
            self._check_aligned(value, 4, rela, "LD_PREL_LO19")
            return self._pack_insn(self._patch_imm19(self._read_insn(rela, elf), value))
        elif rela.type == R_AARCH64_ADR_PREL_LO21:
            value = symval + self._get_rela_addend(rela) - rela.offset
            self._check_range(value, -(1 << 20), 1 << 20, rela, "ADR_PREL_LO21")
            return self._pack_insn(
                self._patch_adr_imm21(self._read_insn(rela, elf), value)
            )
        elif rela.type == R_AARCH64_ADR_PREL_PG_HI21:
            value = self._page(symval + self._get_rela_addend(rela)) - self._page(
                rela.offset
            )
            self._check_range(value, -(1 << 32), 1 << 32, rela, "ADR_PREL_PG_HI21")
            return self._pack_insn(
                self._patch_adr_imm21(self._read_insn(rela, elf), value, page=True)
            )
        elif rela.type == R_AARCH64_ADR_PREL_PG_HI21_NC:
            value = self._page(symval + self._get_rela_addend(rela)) - self._page(
                rela.offset
            )
            return self._pack_insn(
                self._patch_adr_imm21(self._read_insn(rela, elf), value, page=True)
            )
        elif rela.type == R_AARCH64_ADD_ABS_LO12_NC:
            value = symval + self._get_rela_addend(rela)
            return self._pack_insn(
                self._patch_add_imm12(self._read_insn(rela, elf), value, shift12=False)
            )
        elif rela.type == R_AARCH64_LDST8_ABS_LO12_NC:
            value = symval + self._get_rela_addend(rela)
            return self._pack_insn(
                self._patch_ldst_uimm12(self._read_insn(rela, elf), value, 0)
            )
        elif rela.type == R_AARCH64_LDST16_ABS_LO12_NC:
            value = symval + self._get_rela_addend(rela)
            self._check_aligned(value, 2, rela, "LDST16_ABS_LO12_NC")
            return self._pack_insn(
                self._patch_ldst_uimm12(self._read_insn(rela, elf), value, 1)
            )
        elif rela.type == R_AARCH64_LDST32_ABS_LO12_NC:
            value = symval + self._get_rela_addend(rela)
            self._check_aligned(value, 4, rela, "LDST32_ABS_LO12_NC")
            return self._pack_insn(
                self._patch_ldst_uimm12(self._read_insn(rela, elf), value, 2)
            )
        elif rela.type == R_AARCH64_LDST64_ABS_LO12_NC:
            value = symval + self._get_rela_addend(rela)
            self._check_aligned(value, 8, rela, "LDST64_ABS_LO12_NC")
            return self._pack_insn(
                self._patch_ldst_uimm12(self._read_insn(rela, elf), value, 3)
            )
        elif rela.type == R_AARCH64_LDST128_ABS_LO12_NC:
            value = symval + self._get_rela_addend(rela)
            self._check_aligned(value, 16, rela, "LDST128_ABS_LO12_NC")
            return self._pack_insn(
                self._patch_ldst_uimm12(self._read_insn(rela, elf), value, 4)
            )
        elif rela.type == R_AARCH64_TSTBR14:
            value = symval + self._get_rela_addend(rela) - rela.offset
            self._check_range(value, -(1 << 15), 1 << 15, rela, "TSTBR14")
            self._check_aligned(value, 4, rela, "TSTBR14")
            return self._pack_insn(
                self._patch_tbz_imm14(self._read_insn(rela, elf), value)
            )
        elif rela.type == R_AARCH64_CONDBR19:
            value = symval + self._get_rela_addend(rela) - rela.offset
            self._check_range(value, -(1 << 20), 1 << 20, rela, "CONDBR19")
            self._check_aligned(value, 4, rela, "CONDBR19")
            return self._pack_insn(self._patch_imm19(self._read_insn(rela, elf), value))
        elif rela.type == R_AARCH64_JUMP26:
            value = symval + self._get_rela_addend(rela) - rela.offset
            self._check_range(value, -(1 << 27), 1 << 27, rela, "JUMP26")
            self._check_aligned(value, 4, rela, "JUMP26")
            return self._pack_insn(
                self._patch_branch26(self._read_insn(rela, elf), value)
            )
        elif rela.type == R_AARCH64_CALL26:
            value = symval + self._get_rela_addend(rela) - rela.offset
            self._check_range(value, -(1 << 27), 1 << 27, rela, "CALL26")
            self._check_aligned(value, 4, rela, "CALL26")
            return self._pack_insn(
                self._patch_branch26(self._read_insn(rela, elf), value)
            )
        elif rela.type == R_AARCH64_PATCHINST:
            value = symval + self._get_data_addend(rela, elf, 4)
            self._check_range(value, 0, 1 << 32, rela, "PATCHINST")
            return self._pack(value, 4)

        elif rela.type in (
            R_AARCH64_MOVW_GOTOFF_G0,
            R_AARCH64_MOVW_GOTOFF_G0_NC,
            R_AARCH64_MOVW_GOTOFF_G1,
            R_AARCH64_MOVW_GOTOFF_G1_NC,
            R_AARCH64_MOVW_GOTOFF_G2,
            R_AARCH64_MOVW_GOTOFF_G2_NC,
            R_AARCH64_MOVW_GOTOFF_G3,
            R_AARCH64_GOT_LD_PREL19,
            R_AARCH64_LD64_GOTOFF_LO15,
            R_AARCH64_ADR_GOT_PAGE,
            R_AARCH64_LD64_GOT_LO12_NC,
            R_AARCH64_LD64_GOTPAGE_LO15,
        ):
            got_entry = self._proxy_offset(
                rela,
                (R_AARCH64_GLOB_DAT, R_AARCH64_AUTH_GLOB_DAT),
                "the symbol's GOT entry address",
            )
            got_base = self._got_base(rela, elf)
            if rela.type == R_AARCH64_MOVW_GOTOFF_G0:
                return self._apply_mov_signed(rela, elf, got_entry - got_base, 0, 16)
            elif rela.type == R_AARCH64_MOVW_GOTOFF_G0_NC:
                return self._apply_mov_signed(
                    rela, elf, got_entry - got_base, 0, movk=True
                )
            elif rela.type == R_AARCH64_MOVW_GOTOFF_G1:
                return self._apply_mov_signed(rela, elf, got_entry - got_base, 16, 32)
            elif rela.type == R_AARCH64_MOVW_GOTOFF_G1_NC:
                return self._apply_mov_signed(
                    rela, elf, got_entry - got_base, 16, movk=True
                )
            elif rela.type == R_AARCH64_MOVW_GOTOFF_G2:
                return self._apply_mov_signed(rela, elf, got_entry - got_base, 32, 48)
            elif rela.type == R_AARCH64_MOVW_GOTOFF_G2_NC:
                return self._apply_mov_signed(
                    rela, elf, got_entry - got_base, 32, movk=True
                )
            elif rela.type == R_AARCH64_MOVW_GOTOFF_G3:
                return self._apply_mov_signed(rela, elf, got_entry - got_base, 48)
            elif rela.type == R_AARCH64_GOT_LD_PREL19:
                value = got_entry - rela.offset
                self._check_range(value, -(1 << 20), 1 << 20, rela, "GOT_LD_PREL19")
                self._check_aligned(value, 4, rela, "GOT_LD_PREL19")
                return self._pack_insn(
                    self._patch_imm19(self._read_insn(rela, elf), value)
                )
            elif rela.type == R_AARCH64_LD64_GOTOFF_LO15:
                value = got_entry - got_base
                self._check_range(value, 0, 1 << 15, rela, "LD64_GOTOFF_LO15")
                self._check_aligned(value, 8, rela, "LD64_GOTOFF_LO15")
                return self._pack_insn(
                    self._patch_ldst_uimm12(self._read_insn(rela, elf), value, 3)
                )
            elif rela.type == R_AARCH64_ADR_GOT_PAGE:
                value = self._page(got_entry) - self._page(rela.offset)
                self._check_range(value, -(1 << 32), 1 << 32, rela, "ADR_GOT_PAGE")
                return self._pack_insn(
                    self._patch_adr_imm21(self._read_insn(rela, elf), value, page=True)
                )
            elif rela.type == R_AARCH64_LD64_GOT_LO12_NC:
                self._check_aligned(got_entry, 8, rela, "LD64_GOT_LO12_NC")
                return self._pack_insn(
                    self._patch_ldst_uimm12(self._read_insn(rela, elf), got_entry, 3)
                )
            else:
                value = got_entry - self._page(got_base)
                self._check_range(value, 0, 1 << 15, rela, "LD64_GOTPAGE_LO15")
                self._check_aligned(value, 8, rela, "LD64_GOTPAGE_LO15")
                return self._pack_insn(
                    self._patch_ldst_uimm12(self._read_insn(rela, elf), value, 3)
                )

        elif rela.type in (
            R_AARCH64_TLSGD_ADR_PREL21,
            R_AARCH64_TLSGD_ADR_PAGE21,
            R_AARCH64_TLSGD_ADD_LO12_NC,
            R_AARCH64_TLSGD_MOVW_G1,
            R_AARCH64_TLSGD_MOVW_G0_NC,
            R_AARCH64_TLSLD_ADR_PREL21,
            R_AARCH64_TLSLD_ADR_PAGE21,
            R_AARCH64_TLSLD_ADD_LO12_NC,
            R_AARCH64_TLSLD_MOVW_G1,
            R_AARCH64_TLSLD_MOVW_G0_NC,
            R_AARCH64_TLSLD_LD_PREL19,
        ):
            pair_base = self._tls_pair_base(
                rela,
                elf,
                (R_AARCH64_TLS_DTPMOD, R_AARCH64_TLS_DTPREL),
                "the TLS GD/LD GOT entry address",
            )
            got_base = self._got_base(rela, elf)
            if rela.type in (R_AARCH64_TLSGD_ADR_PREL21, R_AARCH64_TLSLD_ADR_PREL21):
                value = pair_base - rela.offset
                self._check_range(value, -(1 << 20), 1 << 20, rela, "TLS ADR_PREL21")
                return self._pack_insn(
                    self._patch_adr_imm21(self._read_insn(rela, elf), value)
                )
            elif rela.type in (R_AARCH64_TLSGD_ADR_PAGE21, R_AARCH64_TLSLD_ADR_PAGE21):
                value = self._page(pair_base) - self._page(rela.offset)
                self._check_range(value, -(1 << 32), 1 << 32, rela, "TLS ADR_PAGE21")
                return self._pack_insn(
                    self._patch_adr_imm21(self._read_insn(rela, elf), value, page=True)
                )
            elif rela.type in (
                R_AARCH64_TLSGD_ADD_LO12_NC,
                R_AARCH64_TLSLD_ADD_LO12_NC,
            ):
                return self._pack_insn(
                    self._patch_add_imm12(
                        self._read_insn(rela, elf), pair_base, shift12=False
                    )
                )
            elif rela.type in (R_AARCH64_TLSGD_MOVW_G1, R_AARCH64_TLSLD_MOVW_G1):
                return self._apply_mov_signed(rela, elf, pair_base - got_base, 16, 32)
            elif rela.type in (R_AARCH64_TLSGD_MOVW_G0_NC, R_AARCH64_TLSLD_MOVW_G0_NC):
                return self._apply_mov_signed(
                    rela, elf, pair_base - got_base, 0, movk=True
                )
            else:
                value = pair_base - rela.offset
                self._check_range(value, -(1 << 20), 1 << 20, rela, "TLSLD_LD_PREL19")
                self._check_aligned(value, 4, rela, "TLSLD_LD_PREL19")
                return self._pack_insn(
                    self._patch_imm19(self._read_insn(rela, elf), value)
                )

        elif rela.type in (
            R_AARCH64_TLSIE_MOVW_GOTTPREL_G1,
            R_AARCH64_TLSIE_MOVW_GOTTPREL_G0_NC,
            R_AARCH64_TLSIE_ADR_GOTTPREL_PAGE21,
            R_AARCH64_TLSIE_LD64_GOTTPREL_LO12_NC,
            R_AARCH64_TLSIE_LD_GOTTPREL_PREL19,
        ):
            got_entry = self._proxy_offset(
                rela,
                (R_AARCH64_TLS_TPREL,),
                "the symbol's TLS IE GOT entry address",
            )
            got_base = self._got_base(rela, elf)
            if rela.type == R_AARCH64_TLSIE_MOVW_GOTTPREL_G1:
                return self._apply_mov_signed(rela, elf, got_entry - got_base, 16, 32)
            elif rela.type == R_AARCH64_TLSIE_MOVW_GOTTPREL_G0_NC:
                return self._apply_mov_signed(
                    rela, elf, got_entry - got_base, 0, movk=True
                )
            elif rela.type == R_AARCH64_TLSIE_ADR_GOTTPREL_PAGE21:
                value = self._page(got_entry) - self._page(rela.offset)
                self._check_range(
                    value, -(1 << 32), 1 << 32, rela, "TLSIE_ADR_GOTTPREL_PAGE21"
                )
                return self._pack_insn(
                    self._patch_adr_imm21(self._read_insn(rela, elf), value, page=True)
                )
            elif rela.type == R_AARCH64_TLSIE_LD64_GOTTPREL_LO12_NC:
                self._check_aligned(got_entry, 8, rela, "TLSIE_LD64_GOTTPREL_LO12_NC")
                return self._pack_insn(
                    self._patch_ldst_uimm12(self._read_insn(rela, elf), got_entry, 3)
                )
            else:
                value = got_entry - rela.offset
                self._check_range(
                    value, -(1 << 20), 1 << 20, rela, "TLSIE_LD_GOTTPREL_PREL19"
                )
                self._check_aligned(value, 4, rela, "TLSIE_LD_GOTTPREL_PREL19")
                return self._pack_insn(
                    self._patch_imm19(self._read_insn(rela, elf), value)
                )

        elif rela.type in (
            R_AARCH64_TLSDESC_LD_PREL19,
            R_AARCH64_TLSDESC_ADR_PREL21,
            R_AARCH64_TLSDESC_ADR_PAGE21,
            R_AARCH64_TLSDESC_LD64_LO12,
            R_AARCH64_TLSDESC_ADD_LO12,
            R_AARCH64_TLSDESC_OFF_G1,
            R_AARCH64_TLSDESC_OFF_G0_NC,
            R_AARCH64_TLSDESC_LDR,
            R_AARCH64_TLSDESC_ADD,
            R_AARCH64_TLSDESC_CALL,
        ):
            if rela.type in (
                R_AARCH64_TLSDESC_LDR,
                R_AARCH64_TLSDESC_ADD,
                R_AARCH64_TLSDESC_CALL,
            ):
                # These relocations are markers for relaxation only.
                return b""

            desc_addr = self._proxy_offset(
                rela,
                (R_AARCH64_TLSDESC, R_AARCH64_AUTH_TLSDESC),
                "the symbol's TLS descriptor entry address",
            )
            got_base = self._got_base(rela, elf)
            if rela.type == R_AARCH64_TLSDESC_LD_PREL19:
                value = desc_addr - rela.offset
                self._check_range(value, -(1 << 20), 1 << 20, rela, "TLSDESC_LD_PREL19")
                self._check_aligned(value, 4, rela, "TLSDESC_LD_PREL19")
                return self._pack_insn(
                    self._patch_imm19(self._read_insn(rela, elf), value)
                )
            elif rela.type == R_AARCH64_TLSDESC_ADR_PREL21:
                value = desc_addr - rela.offset
                self._check_range(
                    value, -(1 << 20), 1 << 20, rela, "TLSDESC_ADR_PREL21"
                )
                return self._pack_insn(
                    self._patch_adr_imm21(self._read_insn(rela, elf), value)
                )
            elif rela.type == R_AARCH64_TLSDESC_ADR_PAGE21:
                value = self._page(desc_addr) - self._page(rela.offset)
                self._check_range(
                    value, -(1 << 32), 1 << 32, rela, "TLSDESC_ADR_PAGE21"
                )
                return self._pack_insn(
                    self._patch_adr_imm21(self._read_insn(rela, elf), value, page=True)
                )
            elif rela.type == R_AARCH64_TLSDESC_LD64_LO12:
                self._check_aligned(desc_addr, 8, rela, "TLSDESC_LD64_LO12")
                return self._pack_insn(
                    self._patch_ldst_uimm12(self._read_insn(rela, elf), desc_addr, 3)
                )
            elif rela.type == R_AARCH64_TLSDESC_ADD_LO12:
                return self._pack_insn(
                    self._patch_add_imm12(
                        self._read_insn(rela, elf), desc_addr, shift12=False
                    )
                )
            elif rela.type == R_AARCH64_TLSDESC_OFF_G1:
                return self._apply_mov_signed(rela, elf, desc_addr - got_base, 16, 32)
            else:
                return self._apply_mov_signed(
                    rela, elf, desc_addr - got_base, 0, movk=True
                )

        elif rela.type in (
            R_AARCH64_AUTH_MOVW_GOTOFF_G0,
            R_AARCH64_AUTH_MOVW_GOTOFF_G0_NC,
            R_AARCH64_AUTH_MOVW_GOTOFF_G1,
            R_AARCH64_AUTH_MOVW_GOTOFF_G1_NC,
            R_AARCH64_AUTH_MOVW_GOTOFF_G2,
            R_AARCH64_AUTH_MOVW_GOTOFF_G2_NC,
            R_AARCH64_AUTH_MOVW_GOTOFF_G3,
            R_AARCH64_AUTH_GOT_LD_PREL19,
            R_AARCH64_AUTH_LD64_GOTOFF_LO15,
            R_AARCH64_AUTH_ADR_GOT_PAGE,
            R_AARCH64_AUTH_LD64_GOT_LO12_NC,
            R_AARCH64_AUTH_LD64_GOTPAGE_LO15,
            R_AARCH64_AUTH_GOT_ADD_LO12_NC,
            R_AARCH64_AUTH_GOT_ADR_PREL_LO21,
        ):
            got_entry = self._proxy_offset(
                rela,
                (R_AARCH64_AUTH_GLOB_DAT,),
                "the symbol's authenticated GOT entry address",
            )
            got_base = self._got_base(rela, elf)
            if rela.type == R_AARCH64_AUTH_MOVW_GOTOFF_G0:
                return self._apply_mov_signed(rela, elf, got_entry - got_base, 0, 16)
            elif rela.type == R_AARCH64_AUTH_MOVW_GOTOFF_G0_NC:
                return self._apply_mov_signed(
                    rela, elf, got_entry - got_base, 0, movk=True
                )
            elif rela.type == R_AARCH64_AUTH_MOVW_GOTOFF_G1:
                return self._apply_mov_signed(rela, elf, got_entry - got_base, 16, 32)
            elif rela.type == R_AARCH64_AUTH_MOVW_GOTOFF_G1_NC:
                return self._apply_mov_signed(
                    rela, elf, got_entry - got_base, 16, movk=True
                )
            elif rela.type == R_AARCH64_AUTH_MOVW_GOTOFF_G2:
                return self._apply_mov_signed(rela, elf, got_entry - got_base, 32, 48)
            elif rela.type == R_AARCH64_AUTH_MOVW_GOTOFF_G2_NC:
                return self._apply_mov_signed(
                    rela, elf, got_entry - got_base, 32, movk=True
                )
            elif rela.type == R_AARCH64_AUTH_MOVW_GOTOFF_G3:
                return self._apply_mov_signed(rela, elf, got_entry - got_base, 48)
            elif rela.type == R_AARCH64_AUTH_GOT_LD_PREL19:
                value = got_entry - rela.offset
                self._check_range(
                    value, -(1 << 20), 1 << 20, rela, "AUTH_GOT_LD_PREL19"
                )
                self._check_aligned(value, 4, rela, "AUTH_GOT_LD_PREL19")
                return self._pack_insn(
                    self._patch_imm19(self._read_insn(rela, elf), value)
                )
            elif rela.type == R_AARCH64_AUTH_LD64_GOTOFF_LO15:
                value = got_entry - got_base
                self._check_range(value, 0, 1 << 15, rela, "AUTH_LD64_GOTOFF_LO15")
                self._check_aligned(value, 8, rela, "AUTH_LD64_GOTOFF_LO15")
                return self._pack_insn(
                    self._patch_ldst_uimm12(self._read_insn(rela, elf), value, 3)
                )
            elif rela.type == R_AARCH64_AUTH_ADR_GOT_PAGE:
                value = self._page(got_entry) - self._page(rela.offset)
                self._check_range(value, -(1 << 32), 1 << 32, rela, "AUTH_ADR_GOT_PAGE")
                return self._pack_insn(
                    self._patch_adr_imm21(self._read_insn(rela, elf), value, page=True)
                )
            elif rela.type == R_AARCH64_AUTH_LD64_GOT_LO12_NC:
                self._check_aligned(got_entry, 8, rela, "AUTH_LD64_GOT_LO12_NC")
                return self._pack_insn(
                    self._patch_ldst_uimm12(self._read_insn(rela, elf), got_entry, 3)
                )
            elif rela.type == R_AARCH64_AUTH_LD64_GOTPAGE_LO15:
                value = got_entry - self._page(got_base)
                self._check_range(value, 0, 1 << 15, rela, "AUTH_LD64_GOTPAGE_LO15")
                self._check_aligned(value, 8, rela, "AUTH_LD64_GOTPAGE_LO15")
                return self._pack_insn(
                    self._patch_ldst_uimm12(self._read_insn(rela, elf), value, 3)
                )
            elif rela.type == R_AARCH64_AUTH_GOT_ADD_LO12_NC:
                return self._pack_insn(
                    self._patch_add_imm12(
                        self._read_insn(rela, elf), got_entry, shift12=False
                    )
                )
            else:
                value = got_entry - rela.offset
                self._check_range(
                    value, -(1 << 20), 1 << 20, rela, "AUTH_GOT_ADR_PREL_LO21"
                )
                return self._pack_insn(
                    self._patch_adr_imm21(self._read_insn(rela, elf), value)
                )

        elif rela.type in (
            R_AARCH64_AUTH_TLSDESC_ADR_PAGE21,
            R_AARCH64_AUTH_TLSDESC_LD64_LO12,
            R_AARCH64_AUTH_TLSDESC_ADD_LO12,
        ):
            desc_addr = self._proxy_offset(
                rela,
                (R_AARCH64_AUTH_TLSDESC,),
                "the symbol's authenticated TLS descriptor entry address",
            )
            if rela.type == R_AARCH64_AUTH_TLSDESC_ADR_PAGE21:
                value = self._page(desc_addr) - self._page(rela.offset)
                self._check_range(
                    value, -(1 << 32), 1 << 32, rela, "AUTH_TLSDESC_ADR_PAGE21"
                )
                return self._pack_insn(
                    self._patch_adr_imm21(self._read_insn(rela, elf), value, page=True)
                )
            elif rela.type == R_AARCH64_AUTH_TLSDESC_LD64_LO12:
                self._check_aligned(desc_addr, 8, rela, "AUTH_TLSDESC_LD64_LO12")
                return self._pack_insn(
                    self._patch_ldst_uimm12(self._read_insn(rela, elf), desc_addr, 3)
                )
            else:
                return self._pack_insn(
                    self._patch_add_imm12(
                        self._read_insn(rela, elf), desc_addr, shift12=False
                    )
                )

        elif rela.type in (
            R_AARCH64_TLSLD_MOVW_DTPREL_G2,
            R_AARCH64_TLSLD_MOVW_DTPREL_G1,
            R_AARCH64_TLSLD_MOVW_DTPREL_G1_NC,
            R_AARCH64_TLSLD_MOVW_DTPREL_G0,
            R_AARCH64_TLSLD_MOVW_DTPREL_G0_NC,
            R_AARCH64_TLSLD_ADD_DTPREL_HI12,
            R_AARCH64_TLSLD_ADD_DTPREL_LO12,
            R_AARCH64_TLSLD_ADD_DTPREL_LO12_NC,
            R_AARCH64_TLSLD_LDST8_DTPREL_LO12,
            R_AARCH64_TLSLD_LDST8_DTPREL_LO12_NC,
            R_AARCH64_TLSLD_LDST16_DTPREL_LO12,
            R_AARCH64_TLSLD_LDST16_DTPREL_LO12_NC,
            R_AARCH64_TLSLD_LDST32_DTPREL_LO12,
            R_AARCH64_TLSLD_LDST32_DTPREL_LO12_NC,
            R_AARCH64_TLSLD_LDST64_DTPREL_LO12,
            R_AARCH64_TLSLD_LDST64_DTPREL_LO12_NC,
            R_AARCH64_TLSLD_LDST128_DTPREL_LO12,
            R_AARCH64_TLSLD_LDST128_DTPREL_LO12_NC,
            R_AARCH64_TLSLE_MOVW_TPREL_G2,
            R_AARCH64_TLSLE_MOVW_TPREL_G1,
            R_AARCH64_TLSLE_MOVW_TPREL_G1_NC,
            R_AARCH64_TLSLE_MOVW_TPREL_G0,
            R_AARCH64_TLSLE_MOVW_TPREL_G0_NC,
            R_AARCH64_TLSLE_ADD_TPREL_HI12,
            R_AARCH64_TLSLE_ADD_TPREL_LO12,
            R_AARCH64_TLSLE_ADD_TPREL_LO12_NC,
            R_AARCH64_TLSLE_LDST8_TPREL_LO12,
            R_AARCH64_TLSLE_LDST8_TPREL_LO12_NC,
            R_AARCH64_TLSLE_LDST16_TPREL_LO12,
            R_AARCH64_TLSLE_LDST16_TPREL_LO12_NC,
            R_AARCH64_TLSLE_LDST32_TPREL_LO12,
            R_AARCH64_TLSLE_LDST32_TPREL_LO12_NC,
            R_AARCH64_TLSLE_LDST64_TPREL_LO12,
            R_AARCH64_TLSLE_LDST64_TPREL_LO12_NC,
            R_AARCH64_TLSLE_LDST128_TPREL_LO12,
            R_AARCH64_TLSLE_LDST128_TPREL_LO12_NC,
            R_AARCH64_TLS_DTPMOD,
            R_AARCH64_TLS_DTPREL,
            R_AARCH64_TLS_TPREL,
        ):
            # These relocations need the final layout of the module's TLS block
            # and, for TPREL, the execution environment's thread pointer model.
            self._missing_context(
                rela,
                "the symbol's TLS module ID and/or its final TLS block offset",
            )

        elif rela.type == R_AARCH64_TLSDESC:
            # Filling a TLS descriptor requires the descriptor contents and
            # resolver state, not just the descriptor's address.
            self._missing_context(
                rela,
                "the TLS descriptor contents and resolver state",
            )
        elif rela.type == R_AARCH64_IRELATIVE:
            # Indirect relative relocations require executing an IFUNC resolver
            # at load time and using its return value.
            self._missing_context(rela, "IFUNC resolver execution and its return value")

        elif rela.type == R_AARCH64_FUNCINIT64:
            # FUNCINIT relocations are specified in terms of generating a
            # run-time IRELATIVE relocation, which this loader cannot synthesize.
            self._missing_context(
                rela,
                "run-time FUNCINIT/IRELATIVE relocation synthesis",
            )

        elif rela.type in (
            R_AARCH64_AUTH_ABS64,
            R_AARCH64_AUTH_RELATIVE,
            R_AARCH64_AUTH_GLOB_DAT,
            R_AARCH64_AUTH_TLSDESC,
            R_AARCH64_AUTH_IRELATIVE,
        ):
            # Pointer-authenticated relocations need PAUTH signing semantics,
            # including SCHEMA(*P), signing keys, and platform-specific PAC rules.
            self._missing_context(
                rela,
                "pointer-authentication signing state and schema data",
            )

        else:
            raise ConfigurationError(
                f"Unknown relocation type for {self._symbol_name(rela)}: "
                f"{hex(rela.type)}"
            )
