#!/usr/bin/env python3
"""Render the use/def corpora as a single review-friendly markdown file.

    python render_corpus.py

Reads every corpus_<isa>.json in this directory and writes CORPUS.md:
one section per ISA, one instruction per table row, with the operand
dicts rendered compactly. CORPUS.md is a derived artifact -- edit the
JSON corpora, then rerun this; do not hand-edit CORPUS.md.
"""

import collections
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "CORPUS.md")

# Display order and pretty names; any corpus not listed here is appended
# in filename order after these.
ORDER = [
    ("x86_64", "x86-64"),
    ("i386", "i386 (x86-32)"),
    ("aarch64", "AArch64"),
    ("arm32", "ARM (ARMv7-A, ARM mode)"),
    ("mips32", "MIPS32 (big-endian)"),
    ("ppc32", "PowerPC32 (big-endian)"),
]


def cell(s):
    """Make a string safe for a markdown table cell."""
    return s.replace("|", "\\|").replace("\n", " ").strip()


def anchor(name):
    """GitHub heading anchor: lowercase, drop punctuation, spaces->hyphens."""
    return "".join(c for c in name.lower() if c.isalnum() or c in " -").replace(
        " ", "-"
    )


def mem(m):
    base = m.get("base")
    index = m.get("index")
    scale = m.get("scale", 1) or 1
    off = int(m.get("offset", 0) or 0)
    size = m.get("size", 0)
    if base is None and index is None:
        inner = f"0x{off & ((1 << 64) - 1):x}"  # absolute address
    else:
        inner = base or ""
        if index:
            term = index if scale == 1 else f"{scale}*{index}"
            inner = f"{inner}+{term}" if inner else term
        if off < 0:
            inner += f"-0x{-off:x}"
        elif off > 0:
            inner += f"+0x{off:x}"
    return f"[{inner}]:{size}"


def operand(o):
    return o["reg"] if "reg" in o else mem(o["mem"])


def opset(items, optional):
    # required operands, then optional ones with a trailing '?'
    parts = [operand(o) for o in items] + [operand(o) + "?" for o in optional]
    return ", ".join(parts) if parts else "\u2014"


def load_corpora():
    named = dict(ORDER)
    paths = sorted(glob.glob(os.path.join(HERE, "corpus_*.json")))
    out = []
    seen = set()
    # listed ISAs first, in ORDER
    for isa, name in ORDER:
        p = os.path.join(HERE, f"corpus_{isa}.json")
        if os.path.exists(p):
            out.append((name, json.load(open(p))))
            seen.add(p)
    # any others
    for p in paths:
        if p in seen:
            continue
        c = json.load(open(p))
        out.append((named.get(c["isa"], c["isa"]), c))
    return out


def main():
    corpora = load_corpora()
    lines = [
        "# Instruction use/def ground-truth corpora\n",
        "Human-readable rendering of `tests/use_def/corpus_*.json` for "
        "review. Generated by `render_corpus.py` -- edit the JSON and "
        "rerun; do not hand-edit this file.\n",
        "Operand notation: registers by name; memory as "
        "`[base+scale*index\u00b10xoffset]:size` (bytes), or `[0xADDR]:size` "
        "for an absolute address. A trailing `?` marks an *optional* "
        "operand (accepted but not required -- e.g. architecturally "
        "undefined flags, hardwired-zero reads).\n",
        "## Contents\n",
    ]
    for name, c in corpora:
        lines.append(
            f"- [{name}](#{anchor(name)}) - {len(c['entries'])} instructions, "
            f"`{c['ghidra_lang']}`"
        )
    lines.append("")

    for name, c in corpora:
        cats = collections.Counter(
            (e.get("categories") or ["?"])[0] for e in c["entries"]
        )
        catstr = ", ".join(f"{k} {v}" for k, v in cats.most_common())
        lines.append(f"## {name}\n")
        lines.append(
            f"{len(c['entries'])} instructions - Ghidra language "
            f"`{c['ghidra_lang']}` - base address "
            f"`0x{c['base_address']:x}`\n"
        )
        lines.append(f"Category breakdown: {catstr}\n")
        lines.append("| # | asm | bytes | uses | defs | notes |")
        lines.append("|--:|-----|-------|------|------|-------|")
        for i, e in enumerate(c["entries"], 1):
            uses = opset(e.get("uses", []), e.get("uses_optional", []))
            defs = opset(e.get("defs", []), e.get("defs_optional", []))
            lines.append(
                f"| {i} | `{cell(e['asm'])}` | `{e['bytes']}` | "
                f"{cell(uses)} | {cell(defs)} | {cell(e.get('notes', '') or '')} |"
            )
        lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    total = sum(len(c["entries"]) for _, c in corpora)
    print(f"wrote {OUT}: {len(corpora)} ISAs, {total} instructions")


if __name__ == "__main__":
    main()
