name: Auto Format

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopen, edited]
  workflow_dispatch:

concurrency:
  group: format-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: smallworld-arc
    permissions:
      contents: write
    outputs:
      changes: ${{ steps.autocommit.outputs.changes_detected }}
    steps:
      - name: Preinit
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs build-essential cmake clang

      - uses: actions/checkout@v3
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[development] -c constraints.txt

      - name: Run formatters (isort & black)
        run: |
          isort . --profile black
          black ./

      - id: autocommit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: isort and black"
          commit_author: GitHub Actions <actions@github.com>

      - name: Summary
        run: |
          echo "changes_detected=${{ steps.autocommit.outputs.changes_detected }}"