name: Commit

on: [push]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[development] -c constraints.txt
      - name: isort
        run: |
          isort . --profile black
          black ./
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: isort and black"
          commit_author: GitHub Actions <actions@github.com>
  Lint:
    needs: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[development] -c constraints.txt
      - name: Lint
        run: |
          isort --check --profile black .
          black --check ./
          flake8 ./
          mypy --ignore-missing-imports ./
