name: Push

on:
  push

jobs:
  Docs:
    runs-on: smallworld-arc    
    steps:
      #- uses: cachix/cachix-action@v15
      #  with:
      #    name: smallworld
      #    authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          
      - name: Checkout
        uses: actions/checkout@v3
        env:
          bot_token: ${{ secrets.BOT_TOKEN }}
        if: ${{ env.bot_token != '' }}
        with:
          token: ${{ secrets.BOT_TOKEN }}

      # blah blah blah blah
      #- name: Cache inputs
      #  env:
      #    cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      #  if: ${{ env.cachix_token != '' }}
      #  run: |
      #    nix run .#printInputsRecursive | cachix push smallworld

      - name: Build devshell
        run: |
          nix -L develop -c true

      - name: Build Test Artifacts
        run: |
          nix build .#tests
          tar -C tests -xvf result/test_binaries.tar
          nix build .#rtos_demo
          cp result/zephyr.elf use_cases/rtos_demo/zephyr.elf

      - name: Build docs
        run: |
          nix develop -c sphinx-build -W -b html docs build/documentation

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/documentation
          # destination_dir: main
          exclude_assets: .gitignore

