name: Release

on:
  release: 
    types: [released]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      TZ: UTC
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[development] -c constraints.txt
      - name: Build
        env:
          PIP_CONSTRAINT: constraints.txt
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: Deploy
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  Docs:
    runs-on: smallworld-arc    
    steps:
      - uses: cachix/cachix-action@v15
        with:
          name: smallworld
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          
      - name: Checkout
        uses: actions/checkout@v3
        env:
          bot_token: ${{ secrets.BOT_TOKEN }}
        if: ${{ env.bot_token != '' }}
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Cache inputs
        env:
          cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
        if: ${{ env.cachix_token != '' }}
        run: |
          nix run .#printInputsRecursive | cachix push smallworld

      - name: Build devshell
        run: |
          nix -L develop -c true

      - name: Build Test Artifacts
        run: |
          nix build .#tests
          tar -C tests -xvf result/test_binaries.tar
          nix build .#rtos_demo
          cp result/zephyr.elf use_cases/rtos_demo/zephyr.elf

      - name: Build docs I really hope
        run: |
          # we have to enter the dev shell for sphinx-build to work?
          nix develop -c "sphinx-build -W -b html docs build/documentation"

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: github-pages
          publish_dir: build/documentation
          # destination_dir: main
          exclude_assets: .gitignore

