name: RTOS Build
on:
  schedule:
    - cron: "00 6 * * sun"
  workflow_dispatch:

jobs:
  Build-RTOS:
    runs-on: smallworld-arc
    steps:
      - name: Install podman
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman

      - uses: actions/checkout@v3

      - name: Build Zephyr SDK Image
        run: |
          cd use_cases/rtos_demo
          podman build -t smallworld-zephyr-sdk -f ./build_elf/zephyr_build.dockerfile .

      - name: Build zephyr.elf Binary
        run: |
          podman run --name smallworld-zephyr-build -v ./build_elf:/opt/build_elf --entrypoint "/opt/build_elf/entrypoint.sh" smallworld-zephyr-sdk
